### ISSUE TITLE
BigInteger fails to initialize in php8.1

### ISSUE THREAD

**Issue by matkatmusic** [phpseclib/phpseclib#1846] opened 2022-09-27 06:37 UTC
I'm experiencing an issue trying to initialize a `BigInteger` in `php8.1`. 
The issue is caused by this line always throwing an exception: 

https://github.com/phpseclib/phpseclib/blob/d39777128aaa1baba492fa339b28e77c1ba9bff4/phpseclib/Math/BigInteger.php#L151

```
           $engines = [
                ['GMP'],
                ['PHP64', ['OpenSSL']],
                ['BCMath', ['OpenSSL']],
                ['PHP32', ['OpenSSL']]
            ];
            foreach ($engines as $engine) {
                try {
                    self::setEngine($engine[0], isset($engine[1]) ? $engine[1] : []);
                    break;
                } catch (\Exception $e) {
                }
```
specifically, this exception: 
```
        $fqmain = 'phpseclib3\\Math\\BigInteger\\Engines\\' . $main;
        if (!class_exists($fqmain) || !method_exists($fqmain, 'isValidEngine')) {
            throw new \InvalidArgumentException("$main is not a valid engine");
        }
```
This causes this constructor to fail with the following error message, because `self::$mainEngine` is `null` when `instanceof` is called
```
    public function __construct($x = 0, $base = 10)
    {
        self::initialize_static_variables();

        if ($x instanceof self::$mainEngine) {
            $this->value = clone $x;
```
Here is the error as reported by `XDebug`:
```
<xdebug:message filename="file:///var/www/html/phpseclib/Math/BigInteger.php" lineno="171" type="Fatal error"><![CDATA[Uncaught Error: Class name must be a valid object or a string]]></xdebug:message></notify>
```
I'm creating an instance of the class like this, as a test:
```
require_once( "../phpseclib/Math/BigInteger.php" );

$bi = new \phpseclib3\Math\BigInteger();
```

**Comment by terrafrost** [comment] 2022-09-27 11:16
Did you install phpseclib with Composer? Are you running Composer's autoloader at the top of your PHP file? eg. `require __DIR__ . '/vendor/autoload.php';`?

I just ask 'cause I'm able to reproduce this issue if I do this:

```php
<?php
include('vendor\phpseclib\phpseclib\phpseclib\Math\BigInteger.php');

$a = new BigInteger();
echo $a;
```
And the reason that would result in the error you're seeing is because the auto loader isn't being called. None of the engines are being auto-loaded when `class_exists` is called and thus no engine is able to be set and thus `self::$mainEngine` is `null`.

phpseclib v1 does _not_ require an autoloader. It explicitly includes everything it needs.
phpseclib v2 _does_ require an autoloader, altho that autoloader need not necessarily be Composer
phpseclib v3 requires _Composer_ as the autoloader

**Comment by matkatmusic** [comment] 2022-09-27 16:46
Hey @terrafrost 
Thanks for getting back to me.  
I did not install phpseclib with Composer.  
I'm not even using Composer, actually, and just learned that I should be using it.  
I set up the framework as a submodule into my project.  
I'm using Docker and have been having trouble configuring it to use Composer. 
Any tips or suggestions on that front?   I know the request is beyond the scope of this phpseclib issue..

**Comment by terrafrost** [comment] 2022-09-27 21:45
What issues have you had with Composer?

In lieu of knowing that, I'd recommend trying this:

```
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/local/bin/composer \
```

**Comment by matkatmusic** [comment] 2022-09-29 18:41
Got it working via this: 
```
RUN echo "start from here"
RUN mkdir -p /var/www/html/chordie
WORKDIR /var/www/html/chordie
COPY ./auth/* .

RUN mkdir -p /usr/local/bin/composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/local/bin/composer/ 

RUN a2ensite chordieapp.local.conf

EXPOSE 80

# CMD ["apachectl", "-D", "FOREGROUND"]
CMD bash -c "php /usr/local/bin/composer/composer.phar update --no-plugins --no-scripts && apachectl -D FOREGROUND"
```
that final `CMD bash` line came from: 
https://stackoverflow.com/questions/46786589/running-composer-install-within-a-dockerfile

**Comment by terrafrost** [comment] 2022-10-03 04:49
If it wasn't persisting the changes even after the Docker container was destroyed I'd wonder if you hadn't [setup your volumes correctly](https://docs.docker.com/engine/reference/run/#volume-shared-filesystems).

That said, since you know got this working imma close this ticket.

Nice job on figuring it out!

**Closed by terrafrost** 2022-10-03 04:49 UTC
