### ISSUE TITLE
Internal Server Error - on some sites

### ISSUE THREAD

**Issue by ernie400** [phpseclib/phpseclib#943] opened 2016-02-08 17:07 UTC
We've been using phpseclib for about a year to push and pull data from SFTP sites but recently encountered a site or two that I cannot get working.  As soon as the script is called we get the "Internal Server Error" page.  This is happening at connection time.  I have looked for logs and only found the following.  

[Mon Feb 08 11:27:29 2016] [error] Can not read response from /usr/local/ZendSvr6/bin/php-cgi.bin (0.0) - [0] There is no error.

Just using the basics and don't know how to debug.  Even upgraded to ver 10.0.1.  
 
```php
<?php
$path = '/www/websmart/htdocs/wsphp/includes/PHPseclib_1.0.1';
set_include_path(get_include_path() . PATH_SEPARATOR . $path);
include 'Net/SSH2.php';
include 'Net/SFTP.php';
include 'Crypt/RSA.php';
include 'Math/BigInteger.php';

define('NET_SSH2_LOGGING', NET_SSH2_LOG_COMPLEX);

$sftp = new Net_SFTP("$server");

if (!$sftp->login("$user", "$password")) 
{
	$subject = "** Error ** SFTP Connection for $name Failed";	
	// send email
	sendmessage(date("F j, Y, g:i a")."** $name connection error ** 
		                  SFTP $name failed to connect. 
		                  Processing stopped...");
	die;
} 

echo $sftp->exec('pwd');
echo $sftp->exec('ls -la');

echo $sftp->getLog();
?>
```
Any help is greatly appreciated. 

Ernie

Looks like others are experiencing the same issue:
http://stackoverflow.com/questions/35175603/phpseclib-example-throws-error-500

**Comment by terrafrost** [comment] 2016-02-09 14:44
`[Mon Feb 08 11:27:29 2016] [error] Can not read response from /usr/local/ZendSvr6/bin/php-cgi.bin (0.0) - [0] There is no error.` isn't that helpful. Also, I'm pretty sure the author of the SO post is the same guy who posted this:

https://github.com/phpseclib/phpseclib/issues/939

Anyway, my response to you would pretty much be the same.

> It's gonna be impossible to say what the error could be without more info.
> 
> If you're not seeing any errors in the web server logs try doing this, at the top:
> 
> ```php
> ini_set('display_errors', 1);
> error_reporting(E_ALL);
> ```

That said...  so you have code to send you an email when `$sftp->login()` returns false. You're calling a custom function - `sendmessage()`. So one possibility is that `sendmessage()` is just not defined. I mean, are you even getting the email? Your post just says you're getting an error 500.

If you aren't getting the email one thing you could do is to put `exit('this far');` before the `sendmessage()`. When you run the script, after that modification, do you see "this far" output on the screen? You could then move the `exit('this far');` to after the `sendmessage()` call. If you then are seeing an error 500 instead of a "this far" error...  well that would imply that the problem is with `sendmessage()`. Either it isn't defined or it has some sort of error within it.

So, I guess first things first. Let me know if you're getting the email and if not do the `exit('this far');` thing.

**Comment by ernie400** [comment] 2016-02-09 14:59
Terrafrost,

 

Actually, it’s not the same person.  (Sorry, it was just a coincidence that someone else encountered the same issue)

I did what you suggested, added exit('this far');, and still the same results.  

 

I’m actually running on an IBM i (AS/400) platform running ZendServer.

 

Any help is greatly appreciated.

Ernie

**Comment by terrafrost** [comment] 2016-02-09 15:17
> Actually, it’s not the same person.  (Sorry, it was just a coincidence that someone else encountered the same issue)

No, I'm pretty sure it is the same person. #939 was posted by a guy with the name of Stantastic and the SO post was posted by a guy with the name of Stantastic as well. I mean, I suppose it could be different people coordinating the efforts, but that'd just be weird.

Also, I asked if you were getting the email and I note that you did not actually answer that question. So I guess I'm just going to have to assume that you didn't.

So I'll just have you do more of the same `exit('this far')` in Net/SSH2.php. You'll need to follow the instructions to the letter cause otherwise this exercise will be useless. Like you didn't post your modified code so idk if you added the `exit('this far')` before or after the `sendmessage()` call so I'm just having to make the assumption that you did it before, even tho I can't know that for sure.

So let's, for now, just verify that login() is being called. So take this function:

```php
    function login($username)
    {
        $args = func_get_args();
        return call_user_func_array(array(&$this, '_login'), $args);
    }
```

...and replace it with this:

```php
    function login($username)
    {
exit('login called');
        $args = func_get_args();
        return call_user_func_array(array(&$this, '_login'), $args);
    }
```

This won't fix the problem but it'll tell me if login() is being called. If it is and "login called" is being output then we'll delve into the `_login` method.

**Comment by ernie400** [comment] 2016-02-09 15:43
Wow, what will it take to convince you that is not the same person.  

I’m and RPG programmer on the IBM system, that has jumped into the PHP world and is asking for assistance.

 

You are correct to assume that I did not received the email.

I made the changes you suggested to Net/SSH2.php.  Ran the script and receive the same error.  The browser never display “login called” but did get “Internal Server Error”.

 

Thanks,

Ernie

**Comment by ernie400** [comment] 2016-02-10 13:19
Terrafrost,  

 

I can supply an SFTP server for you to try.  It’s the one that’s failing when I try.

 

Thanks,

Ernie

**Comment by terrafrost** [comment] 2016-02-10 15:00
> Wow, what will it take to convince you that is not the same person.
> 
> I’m and RPG programmer on the IBM system, that has jumped into the PHP world and is asking for assistance.

Yes, but you did not post #939. This issue - the issue that **you** posted - is #943. I mean, I guess you could have posted both, with different accounts, but having multiple accounts would be a violation of github.com's TOS..

Anyway, I'll look at the rest of your post shortly.

Thanks!

**Comment by terrafrost** [comment] 2016-02-10 15:07
I think some of the confusion is that you're reading this via email. In my orig post I said this:

> Also, I'm pretty sure the author of the SO post is the same guy who posted this:
> 
> #939 

github.com turns `#939` into a link to https://github.com/phpseclib/phpseclib/issues/939 but on email it might remain `#939`. So when I said "this" I was refering to the link that on github.com would follow whereas you might have just seen a random `#939` and not know what it was referring to idk.

**Comment by ernie400** [comment] 2016-02-10 15:28
Terrafrost, how can I provide you the credentials to the test SFTP server?
Via emai?  I believe you have my email address.
Thanks,
Ernie

**Comment by terrafrost** [comment] 2016-02-10 16:17
You can email the credentials to terrafrost@php.net. That said, my current working theory is that it's more an environmental issue on your end. I mean, there's no harm in my attempting to connect from my own machine, but...  well, in your code, can you add `exit('this far x1');` before `$sftp = new Net_SFTP("$server");`? If you see "this far x1" can you then try moving the `exit('this far x1');` line to after `$sftp = new Net_SFTP("$server");`?

ie. what I'm thinking is that the include's are failing and that the fatal error is due to the fact that `Net_SFTP` just isn't a class that exists. If you were doing `require`, per this theory, it'd be dying when you're attempting to set the `require`'s, but you're not, so I'm thinking it's dying on your attempt to initialize the `Net_SFTP` object.

**Comment by ernie400** [comment] 2016-02-10 16:52
Both scenarios worked.  I saw 'this far x1' on the page when testing before and after $sftp = new Net_SFTP("$server");.

**Comment by terrafrost** [comment] 2016-02-10 22:31
I was able to login with 1.0.1 and the server name / username / password you gave me (I sent you a separate email with the code).

So let's recap what we know so far.

The constructor is being called but Net_SSH2's login() method isn't. But I guess that makes sense for Net_SFTP now that I look at the source code for the login() function for that.

So...

In Net/SFTP.php, find this:

```php
#
#-----[ OPEN ]------------------------------------------
#
Net/SFTP.php
#
#-----[ FIND ]------------------------------------------
#
    function login($username)
    {
#
#-----[ AFTER, ADD ]------------------------------------
#
exit('login called');
#
#-----[ FIND ]------------------------------------------
# if that works
#
        if ($response === false) {
            // from PuTTY's psftp.exe
#
#-----[ BEFORE, ADD ]-----------------------------------
#
exit('this far x2');
#
#-----[ FIND ]------------------------------------------
# if that works
#
        $this->pwd = $this->_realpath('.');
#
#-----[ BEFORE, ADD ]-----------------------------------
#
exit('this far x3');
```

**Comment by ernie400** [comment] 2016-02-11 13:02
terrafrost,
I tried your suggestions and it failed at exit('this far x2');

**Comment by terrafrost** [comment] 2016-02-11 16:43
> I tried your suggestions and it failed at exit('this far x2');

So you're saying that it did not echo out `this far x2`? That the only output you saw was `login called`?

if so then let's undo the changes you previously made and do this:

```php
#
#-----[ OPEN ]------------------------------------------
#
Net/SFTP.php
#
#-----[ FIND ]------------------------------------------
#
        if (!call_user_func_array(array(&$this, '_login'), $args)) {
            return false;
        }
#
#-----[ AFTER, ADD ]------------------------------------
#
exit('this far x4');
#
#-----[ FIND ]------------------------------------------
# if that works
#
        if (!$this->_send_binary_packet($packet)) {
            return false;
        }
#
#-----[ AFTER, ADD ]------------------------------------
#
exit('this far x5');
```

**Comment by ernie400** [comment] 2016-02-11 16:51
terrafrost, it failed at exit('this far x4');.  It did not echo 'this far x4' but received "Internal Server Error".

**Comment by terrafrost** [comment] 2016-02-11 18:08
Try this:

```php
#
#-----[ OPEN ]------------------------------------------
#
Net/SFTP.php
#
#-----[ FIND ]------------------------------------------
#
        if (!call_user_func_array(array(&$this, '_login'), $args)) {
            return false;
        }
#
#-----[ BEFORE, ADD ]-----------------------------------
#
exit('this far x6');
```

If that works but `this far x4` doesn't then what I'd be wondering is if maybe `call_user_func_array` is disabled on your server via the `disable_functions` php.ini directive:

http://php.net/manual/en/ini.core.php#ini.disable-functions

**Comment by terrafrost** [comment] 2016-02-11 18:09
Also, please post your `phpinfo()`. Thanks!

**Comment by ernie400** [comment] 2016-02-11 18:42
terrafrost, you are correct.  It did echo 'this far x6'.  I have also attached my phpinfo().
Thanks,
Ernie

[phpinfo.pdf](https://github.com/phpseclib/phpseclib/files/126902/phpinfo.pdf)

**Comment by terrafrost** [comment] 2016-02-12 04:51
So it looks like `disable_functions` doesn't have anything added to it.

Anyway, you gave me the credentials for the box you're trying to login to - what about the box you're trying to login from? Is that something you could provide me with?

Anyway, in lieu of that, can you try this?:

```php
#
#-----[ OPEN ]------------------------------------------
#
Net/SFTP.php
#
#-----[ FIND ]------------------------------------------
#
        if (!call_user_func_array(array(&$this, '_login'), $args)) {
            return false;
        }
#
#-----[ AFTER, ADD ]------------------------------------
#
exit('this far x7');
```

**Comment by ernie400** [comment] 2016-02-12 14:54
terrafrost, 
I cannot thank you enough for all the help.  
You have been great working with me trying to resolve this issue.  
I'm happy to inform you that **the issue has been resolved**.
I upgraded PHP from Version 5.4.29 to  5.6.15 and the issue corrected itself.
I cannot believe it was that simple.
Thanks again....
Ernie

**Closed** 2016-02-12 14:54 UTC
Labels: support
