### ISSUE TITLE
PHP 7 deprecated errors

### ISSUE THREAD

**Issue by execut** [phpseclib/phpseclib#734] opened 2015-07-13 07:05 UTC
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Net_SSH2 has a deprecated constructor in phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3876

**Comment by bantu** [comment] 2015-07-13 07:12
Already fixed in 2.0 and master

**Comment by bantu** [comment] 2015-07-13 07:39
This can not be implemented for 1.0 due to PHP4 compatibility.

**Closed by bantu** 2015-07-13 07:39 UTC

**Comment by pineapple-it-solutions** [comment] 2019-04-02 15:25
To solve the problem, you need to change the name of the manufacturer, in each class used (where the error appears).

Example:
"Crypt_Hash has a deprecated constructor in <b>/home/e42p4zsf/AFS/front/utils/phpseclib/Crypt/Hash.php</b> on line <b>82</b>"

Change the name of the constructor as follows:

from:

 function Crypt_Hash($hash = 'sha1')

to:

function __construct($hash = 'sha1')

**Comment by bantu** [comment] 2019-04-02 16:08
@pineapple-it-solutions We recommend switching to version 2.0 of phpseclib instead. See https://github.com/phpseclib/phpseclib/issues/734#issuecomment-120834661

**Comment by terrafrost** [comment] 2019-04-02 21:54
This isn't even an issue on the 1.0 branch.

https://3v4l.org/5qXvi demonstrates that 3v4l.org will report the issue as an error when it is an issue.

https://3v4l.org/NHd8n demonstrates that when the PHP5-style constructor precedes the PHP4-style constructor that no error will be issued.

In the 1.0 branch of Crypt/Hash.php the PHP5-style constructor precedes the PHP4-style constructor:

https://github.com/phpseclib/phpseclib/blob/1.0/phpseclib/Crypt/Hash.php

If you're having this issue then I'm not able to reproduce it. phpseclib 1.0 is unit tested on Travis CI and it's not even an issue on Travis CI. You'll need to post your `phpinfo()` output but idk I'm just extremely skeptical that this is a legit issue for the reasons I have already presented.
