### ISSUE TITLE
ErrorException: fclose() expects parameter 1 to be resource, null given

### ISSUE THREAD

**Issue by jamielsharief** [phpseclib/phpseclib#1405] opened 2019-09-16 10:01 UTC
Getting `ErrorException: fclose() expects parameter 1 to be resource, null given` with new update.

Here is the trace

/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:4122
/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:3167
/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3157
/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3173

**Comment by jamielsharief** [comment] 2019-09-16 11:29
https://github.com/phpseclib/phpseclib/pull/1406

**Comment by terrafrost** [comment] 2019-09-16 12:15
Here's the commit that introduced the issue:

https://github.com/phpseclib/phpseclib/commit/fbf36728fdbba5f62e33e61e6ea00f754021cc4e

That said, I am, none-the-less, curious what you're doing for it to be an issue in the first place.

```php
$ssh = new SSH2('127.0.0.1');

exit;
```
That'll reproduce the issue. But this won't:

```php
$ssh = new SSH2('127.0.0.1');
$ssh->login('zzz', 'zzz');

exit;
```
At least it doesn't for me. If there are circumstances that can render `$this->fsock` as null, after it was already a resource, I'm not aware of them. For example...

```php
$fsock = fsockopen('127.0.0.1', 22);
fclose($fsock);
fclose($fsock);
```
Even that change won't give the error you're seeing. At least not the exact error. It'll give a `Warning: fclose(): supplied resource is not a valid stream resource` error.

Your PR won't work because, when a connection is closed prematurely (eg. a "Connection closed by server" error is issued), `$this->bitmap` is set to 0. `isConnected` is looking for a non-0 value (`($this->bitmap & self::MASK_CONNECTED)`) and in this case `$this->fsock` would still be a resource.

(`$this->bitmap` is set to `self::MASK_CONNECTED in `_connect()`)

Here's what I'm thinking:

```php
#
#-----[ OPEN ]------------------------------------------
#
Net/SSH2.php
#
#-----[ FIND ]------------------------------------------
#
        fclose($this->fsock);
#
#-----[ REPLACE WITH ]----------------------------------
#
        if (is_resource($this->fsock) && get_resource_type($this->fsock) == 'stream') {
            fclose($this->fsock);
        }
```

**Comment by jamielsharief** [comment] 2019-09-16 12:39
Since your curious here are the exact details (this is the travis build log)
https://travis-ci.org/originphp/framework/jobs/585484367

This test causes the issue:
https://github.com/originphp/framework/blob/master/tests/TestCase/Storage/Engine/SftpEngineTest.php#L100

The source code where it happens
https://github.com/originphp/framework/blob/master/src/Storage/Engine/SftpEngine.php#L101

It happens when triggering an exception (or at least in PHPunit)

**Comment by jamielsharief** [comment] 2019-09-16 13:12
Note, I  was able to recreate issue straightaway using the example code on your website.

composer require phpseclib/phpseclib:~2.0

<?php
require __DIR__ . '/vendor/autoload.php';
use phpseclib\Net\SFTP;

 $sftp = new SFTP('https://www.originphp.com');
        if (!$sftp->login('username', 'password')) {
            exit('Login Failed');
        }

and it gives

**Comment by jamielsharief** [comment] 2019-09-16 13:14
Note, I  was able to recreate issue straightaway using the example code on your website.

`composer require phpseclib/phpseclib:~2.0`

Created a file

```
<?php
require __DIR__ . '/vendor/autoload.php';
use phpseclib\Net\SFTP;

 $sftp = new SFTP('https://www.originphp.com');
        if (!$sftp->login('username', 'password')) {
            exit('Login Failed');
        }
```
and it gives

```
Warning: fclose() expects parameter 1 to be resource, bool given in /code/phpseclib/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 4122
```

**Comment by jamielsharief** [comment] 2019-09-16 13:18
I accidentally triggered it again

 $sftp = new SFTP('www.invalidcomaind.com');
        if (!$sftp->login('username', 'password')) {
            exit('Login Failed');
        }

**Comment by chrisguitarguy** [comment] 2019-09-16 17:21
I hit a similar issue to this, but `$this->fsock` was `false` not null as a result of an invalid host name. Because `fsockopen` returned `false`, I'd guess.

Same as this comment: https://github.com/phpseclib/phpseclib/issues/1402#issuecomment-531804865

Eg.

```
fclose() expects parameter 1 to be resource, bool given

/.../vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:125
/.../vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:4122
/.../vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:3167
/.../vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3157
/.../vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3173
...
```

**Comment by terrafrost** [comment] 2019-09-16 19:14
I'm gonna get a fix out for this this evening (after I get home from work) and will release a new version.

Thanks!

**Closed** 2019-09-17 03:40 UTC

**Comment by terrafrost** [comment] 2019-09-17 03:48
I made a new 2.0 release that should fix this issue.

Thanks!
