### ISSUE TITLE
Cannot login into SFTP Server - get "size error" ?

### ISSUE THREAD

**Issue by ivpfals** [phpseclib/phpseclib#1163] opened 2017-08-07 06:07 UTC
Hi,

i'm using PHPSeclib now for many years with success, however today I got an error during the login phase to a SFTP only server which never occured before. 

The following error occured:

```
Notice: Invalid size in /data/devel/phpseclibtest/phpseclib/Net/SSH2.php on line 3065

Call Stack:
    0.0003     363656   1. {main}() /data/devel/phpseclibtest/sshtest.php:0
    0.0101    1381224   2. phpseclib\Net\SFTP->login() /data/devel/phpseclibtest/sshtest.php:35
    0.0101    1382000   3. call_user_func_array:{/data/devel/phpseclibtest/phpseclib/Net/SFTP.php:404}() /data/devel/phpseclibtest/phpseclib/Net/SFTP.php:404
    0.0101    1382408   4. phpseclib\Net\SFTP->_login() /data/devel/phpseclibtest/phpseclib/Net/SFTP.php:404
    0.1504    3232776   5. phpseclib\Net\SFTP->_login_helper() /data/devel/phpseclibtest/phpseclib/Net/SSH2.php:1967
    0.1507    3232824   6. phpseclib\Net\SFTP->_get_binary_packet() /data/devel/phpseclibtest/phpseclib/Net/SSH2.php:2002
    0.2177    3232880   7. user_error() /data/devel/phpseclibtest/phpseclib/Net/SSH2.php:3065


Notice: Connection closed by server in /data/devel/phpseclibtest/phpseclib/Net/SSH2.php on line 2004

Call Stack:
    0.0003     363656   1. {main}() /data/devel/phpseclibtest/sshtest.php:0
    0.0101    1381224   2. phpseclib\Net\SFTP->login() /data/devel/phpseclibtest/sshtest.php:35
    0.0101    1382000   3. call_user_func_array:{/data/devel/phpseclibtest/phpseclib/Net/SFTP.php:404}() /data/devel/phpseclibtest/phpseclib/Net/SFTP.php:404
    0.0101    1382408   4. phpseclib\Net\SFTP->_login() /data/devel/phpseclibtest/phpseclib/Net/SFTP.php:404
    0.1504    3232776   5. phpseclib\Net\SFTP->_login_helper() /data/devel/phpseclibtest/phpseclib/Net/SSH2.php:1967
    0.2182    3232824   6. user_error() /data/devel/phpseclibtest/phpseclib/Net/SSH2.php:2004

ERROR!

Login failure - Please check username and password!
```

I've tripple-checked the credentials, everything is absolutly correct. Using the sftp command from OpenSSH (OpenSSH_6.6.1p1) works fine, no connection problems.

Also i've tested with phpseclib2 (the output above is from 2.0 branch) and with phpseclib1, both give exact the same error.

I've no idea what else I could try, hopefully you can track down that problem. If required i can provide also the debugging logs.

Best regards

Sascha

**Comment by terrafrost** [comment] 2017-08-08 03:11
It most likely means that the diffie-hellman key exchange encountered an error. More specifically, I suspect what it means is that the server has a buggy implementation of the symmetric key algorithm that was negotiated.

Seeing the log files would be helpful to me.

One thing that might to you...

```
#
#-----[ OPEN ]------------------------------------------
#
Net/SSH2.php
#
#-----[ FIND ]------------------------------------------
#
        $encryption_algorithms = array(
            // from <http://tools.ietf.org/html/rfc4345#section-4>:
            'arcfour256',
            'arcfour128',
#
#-----[ REPLACE WITH ]----------------------------------
#
        $encryption_algorithms = array(
            // from <http://tools.ietf.org/html/rfc4345#section-4>:
            //'arcfour256',
            //'arcfour128',
```

**Comment by ivpfals** [comment] 2017-08-08 05:23
Hi,

thanks for your feedback. Commenting out the lines you've mentioned solved the connection problem, so your assumption seems to be correct :)

Unfortunately I cannot change the destination server, so I would go and leave these two arcfour algos commented out. 
Also I've attached here the log of the connection with arcfour128/256 enabled, so you may find a workaround for it.

Any chance to make these arcfour algos configurable ? I really would like to be in sync with updates of your libraries, and changing the code on my own to disable them makes it harder to update your libs...

A big thank you for your superb work!!!

Best regards,

Sascha

[log.txt](https://github.com/phpseclib/phpseclib/files/1206973/log.txt)

**Comment by terrafrost** [comment] 2017-08-08 05:43
#1156 was a PR someone submitted to do just that but...  well what happens if someone decides to include an algorithm that phpseclib doesn't support? Also, it'd be nice if they could extend this out to other algorithms as well (key exchange algo, hmac algorithm, compression, etc).

I could make the changes myself but I'm holding off for the time being in the hopes that they will..

**Comment by ivpfals** [comment] 2017-08-08 05:48
Ah okay I see! So I will wait, too and for the time being document the code change in my project, so that I won't forget it when updating phpseclib.

**Comment by terrafrost** [comment] 2017-08-26 14:55
Would you be able to provide me with the IP address of the server that has this problem? I don't need a username or password - logging in with a fake username would be sufficient to allow me to reproduce the problem.

What I'm thinking I can do is make it so that if the packet doesn't decrypt correctly and that the selected cipher is arcfour128 or arcfour256 that it recreates the the cipher object. To test it out, however, I need to be able to connect to a server that demonstrates the problem and none of the servers I have access to (existing servers or new servers on fresh Linux installs) demonstrate it.

Thanks!

**Comment by terrafrost** [comment] 2017-08-27 01:25
https://github.com/phpseclib/phpseclib/issues/1171#issuecomment-325170715 should fix this so that the above work around is no longer necessary.

**Comment by terrafrost** [comment] 2017-08-27 19:34
The commit mentioned in https://github.com/phpseclib/phpseclib/issues/1171#issuecomment-325170715 has been merged into 1.0 / 2.0 / master so I'm going to go ahead and close this since the issue should now be resolved.

**Closed by terrafrost** 2017-08-27 19:35 UTC

**Comment by ivpfals** [comment] 2017-08-30 06:50
FYI: I've got now the information what exactly was running on the serverside:

ProFTPd with mod_sftp running on Linux (SLES 12sp2)

There is also a problem with SFTP Protocol Version 3, if this is enabled on ProFTPd it is not possible to fetch the dirlist using rawlist()! 
The Admin changed the Protocol Version to 2 and rawlist() works, so there seems to be some kind of incompatibility between phpseclib 1.0/2.0 and SFTP v3.

**Comment by terrafrost** [comment] 2017-08-30 12:49
You'd be better off posting this as a new issue. The issue you described in your first post has been fixed and the issue you're describing now is a wholly unrelated one.

That said, my gut instinct is to say that this is just another bug in your SFTP server.

Anyway, I could try to reproduce the problem myself but suspect that would be very difficult. Maybe a Vagrantfile could be developed that'd enable anyone to reproduce the problem but again, that could be quite difficult. Like for the initial problem you had...  developing a Vagrantfile would require downloading an old version of OpenSSL and compiling it. OpenSSL's own dependencies might have developed incompatibilities so you might need to download old versions of it's dependencies. Then you'd have to download OpenSSH and compile that against the old version of OpenSSL. And it seems quite possible that not just any version of OpenSSH would do - that you'd need to download a historical version of that as well.

All in all it'd be a PITA and I suspect a Vagrantfile for ProFTPd that demonstrates the problem could be a similar PITA as well.

The easiest approach for me would be if you gave me an account on the server to connect to. You could email this info to terrafrost@php.net.

In lieu of that seeing the SSH logs might help. You can get them by doing `define('NET_SSH2_LOGGING', 2);` and then `echo $ssh->getLog();` after the problem occurs.

Whatever you do, if you would make a reply please make a new post instead so it can show up as being open instead of this one, which I've closed as being resolved.

Thanks!
