### ISSUE TITLE
PHP7 Requirement breaking builds

### ISSUE THREAD

**Issue by andrewandante** [phpseclib/phpseclib#1066] opened 2016-11-30 13:01 UTC
We have a project where we were using some of the features from dev-master (specifically, `phpseclib\Crypt\RSA::load()`) while running on php 5.6.22. The latest release of master has bumped the PHP requirement to 7, which is breaking our builds, and there exists no tag that contains everything we need. I tried using:

```json
"require": {
		"phpseclib/phpseclib": "dev-master#865904f636a21693fddfbff53bf1472dcd999fc7"
}
```

But due to [this quirk](https://getcomposer.org/doc/04-schema.md#package-links) it still picks up the PHP version 7 constraint.

Could you tag a final release in line with that commit, or up to the last point in master where PHP <7 was still available? For now I am using my own fork.

Thanks!

Andrew

**Comment by terrafrost** [comment] 2016-11-30 14:45
Ya'll should not be using the master branch. The API is unstable. It's changed quite a bit, already, from the 2.0 branch, and the change is only going to become that much more profound as further development continues.

If I created a tag for the master branch then - and correct me if I'm wrong - but wouldn't composer install that when you do `composer require phpseclib/phpseclib`? Like right now it picks up the latest tagged release, which is 2.0.4. But it seems like that would change if I tagged a release for the master branch? Keep in mind I'm not a composer expert - my understanding is, I'd say, fairly basic.

Anyway, that said, my latest PR does lower the version requirements back down to 5.6:

https://github.com/phpseclib/phpseclib/pull/1065

I'll probably let it sit for a week or two to let people opine in but if I don't get any feedback in that time I'll just merge it (as I did with the PR that increased the version req - #1061)

**Comment by andrewandante** [comment] 2016-11-30 15:43
I'm not sure who pulled it in first, but I believe that it is determined based on our `minimum-stability` requirement, which in this case is "dev". I believe that if we had our requirements set to "stable" we would have pulled in `2.0.x`, but we have other packages in unstable versions that we depend on.

I agree that we should have been tighter on our constraints - so I'm trying to lock it down to `^2.0` at the moment - the problem is that there is currently no tag available that satisfies all constraints - hence the fork.

Will future releases continue to be PHP 5.6 compliant?

Also, I checked out the PR, I don't see a `composer.json` change, am I just being blind?

Thanks for responding so quickly!

**Comment by terrafrost** [comment] 2016-11-30 16:18
> Will future releases continue to be PHP 5.6 compliant?

I believe so. Nothing PHP7 offers is exciting enough to break PHP5.6 compatibility imho. I mean, PHP7 introduces, for example, `deflate_init`, which is a function I think I might make SSH2.php use, but I can do `function_exists` to make it work on PHP5.6. Right now in master what doesn't work with PHP5.6 are arrays being used in `define()` statements. In my PR I switched to using arrays with class constants, which facilitates auto-loading and re-use of these ASN.1 "maps". The ability to re-use these "maps" is enough to justify upping the version reqs to PHP5.6.

At the time I did the PR request that was merged last night that upped the reqs to PHP7...  in my early testing it seemed like the `+` operator worked with `define()` but not with `const`. I was wrong, however. I'm not sure what led me to that wrong conclusion but I eventually realized that I was wrong. But at the time...  I still wanted the ASN1 "maps" to live independently of classes that required initialization. This requirement can be achieved with class constants much more elegantly but at the time I didn't realize that.

> Also, I checked out the PR, I don't see a `composer.json` change, am I just being blind?

Ya know...  that's a good point lol. I updated .travis.yml but not composer.json. It looks like composer.json still says it works on >= 5.3.3.

**Comment by andrewandante** [comment] 2016-12-01 08:38
Nice, good to hear. We'll keep an eye on updates. Appreciate the quick feedback and sound reasoning!

**Comment by bantu** [comment] 2016-12-27 13:24
@andrewandante If your minimum-stability allows you to receive unstable code, this is the expected behaviour. Consider setting minimum-stability to stable and allow unstable code on a package basis. See composer documention on how to do that.

I take it that this issue is already resolved.

**Closed by bantu** 2016-12-27 13:24 UTC
Labels: support
