### ISSUE TITLE
SSH-Ed25519

### ISSUE THREAD

**Issue by Esysteme** [phpseclib/phpseclib#1279] opened 2018-06-11 16:52 UTC
Hello,

it is a chance to see an implementation for ssh-ed25519 in phpseclib ?

**Comment by terrafrost** [comment] 2018-06-11 17:32
Yes. I actually posted a status update last night about the status of Ed25519 in phpseclib:

https://github.com/phpseclib/phpseclib/issues/1082#issuecomment-396122366

**Comment by Esysteme** [comment] 2018-06-12 09:56
thx you ;)

**Comment by bantu** [comment] 2018-11-08 11:03
Closing this as a duplicate of #1082 and #1309

**Closed by bantu** 2018-11-08 11:03 UTC
