### ISSUE TITLE
Unable to open channel - Consecutive Execs

### ISSUE THREAD

**Issue by lukepolo** [phpseclib/phpseclib#1009] opened 2016-07-08 01:42 UTC
I am writing a provisioning script to setup my server for me. Now everything seems to be working except it seems that the connection is being shut down early? 

```
ErrorException (E_USER_NOTICE)
Unable to open channel

```

 I am first connecting via SSH , then running lots of commands (50 or more) by running 

`run('do some linux stuff here');
`

Below is more code 

```
    public function ssh($ip)
    {
        $key = new RSA();
        $key->setPassword(env('SSH_KEY_PASSWORD'));
        $key->loadKey(file_get_contents('/home/vagrant/.ssh/id_rsa'));

        $ssh = new SSH2($ip);

        $ssh->enableQuietMode();

        if (!$ssh->login('root', $key)) {
            exit('Login Failed');
        }

        $this->session = $ssh;
    }
}

 public function run($command, $read = false)
    {
        $results = $this->session->exec($command.";");

        if(!empty($error = $this->session->getStdError())) {
            \Log::error($error);
        }

        if(!empty($results)) {
            \Log::info($results);
        }

        if($read) {
            return $this->session->read();
        }
    }


```

Is there a problem with how im doing it , is there a better way ?

**Comment by terrafrost** [comment] 2016-07-09 21:53
Sorry for the delay - been busy at work. Could you get me the SSH logs? You can enable SSH logging by doing `define('NET_SSH2_LOGGING', true);` at the top and then `echo $ssh->getLog()` after. If you're doing 50 commands my guess is that the log would be about 1mb in size (SSH logs are capped at that size - the cap can be changed but that's the default cap but it should be more than enough for me to figure out what's going on).

Thanks!

**Comment by liucf** [comment] 2016-08-19 13:23
@lukepolo have you solve this issue. i got exactly same as yours.. please help.. thanks...

**Comment by themazim** [comment] 2016-09-16 09:18
run into this too, any advice?

**Comment by lukepolo** [comment] 2016-09-16 12:58
If it fails i just reconnect. And run it again. Seems to work just fine.

**Comment by terrafrost** [comment] 2016-09-18 20:50
SSH logs would help me diagnose the issue..

**Comment by thadin** [comment] 2016-10-10 14:30
I am getting the "Unable to open channel in ./vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3273" message as well when using the `exec` method.

Below is a code snippet, depending on the `$useExec` boolean, the code either works or it doesn't. I'm hoping to get the exec version working because the code is cleaner and I'm going to have to enter more commands in the future.
I'm connecting with a Cisco router, so it might not follow the latest SSH spec.

```php
<?php

define('NET_SSH2_LOGGING', true);

$useExec = true;

$ip   = long2ip($input['ip']);
$port = $input['port'] ?: 22;
$ssh  = new SSH2($ip, $port);

$config = null;

if (!$ssh->login($input['user'], $input['pass'])) {
    user_error('Unable to login to '.$ip);
} else {
    $prompt = trim($ssh->read());
   
    $ssh->write("terminal length 0\n");
    $ssh->read($prompt);
    
    if ($useExec) {
        $config = $ssh->exec('show running-config | begin !');
    } else {
        $configCmd = "show running-config | begin !\n";
        $ssh->write($configCmd);
        
        $config = $ssh->read($prompt);
        $config = substr($config, strlen($configCmd), -strlen($prompt));
        $config = trim($config);
    }
    
    if (!$config || substr($config, 0, 1) == '^') {
        echo implode("\n", $ssh->getLog());
        user_error('Unable to retrieve config for '.$ip);
        $config = null;
    }
}
```

Log below:

> <-
->
<- NET_SSH2_MSG_KEXINIT (since last: 0.0327, network: 0.0107s)
-> NET_SSH2_MSG_KEXINIT (since last: 0.0109, network: 0.0001s)
-> NET_SSH2_MSG_KEXDH_INIT (since last: 0.0139, network: 0s)
<- NET_SSH2_MSG_KEXDH_REPLY (since last: 0.274, network: 0.2739s)
-> NET_SSH2_MSG_NEWKEYS (since last: 0.0056, network: 0s)
<- NET_SSH2_MSG_NEWKEYS (since last: 0, network: 0s)
-> NET_SSH2_MSG_SERVICE_REQUEST (since last: 0.0008, network: 0s)
<- NET_SSH2_MSG_SERVICE_ACCEPT (since last: 0.2172, network: 0.2171s)
-> NET_SSH2_MSG_USERAUTH_REQUEST (since last: 0.0002, network: 0s)
<- NET_SSH2_MSG_USERAUTH_BANNER (since last: 0.0001, network: 0s)
<- NET_SSH2_MSG_USERAUTH_SUCCESS (since last: 0.0112, network: 0.0112s)
-> NET_SSH2_MSG_CHANNEL_OPEN (since last: 0.0001, network: 0s)
<- NET_SSH2_MSG_CHANNEL_OPEN_CONFIRMATION (since last: 0.011, network: 0s)
-> NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0001, network: 0s)
<- NET_SSH2_MSG_CHANNEL_SUCCESS (since last: 0.0106, network: 0.0106s)
-> NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0001, network: 0s)
<- NET_SSH2_MSG_CHANNEL_SUCCESS (since last: 0.0109, network: 0s)
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0003, network: 0.0001s)
-> NET_SSH2_MSG_CHANNEL_DATA (since last: 9.9883, network: 0.0001s)
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0108, network: 0.0001s)
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0001, network: 0s)
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0001, network: 0s)
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0002, network: 0.0001s)
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0003, network: 0s)
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0.0001s)
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0001, network: 0s)
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0001, network: 0.0001s)
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0002, network: 0s)
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0003, network: 0.0001s)
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0003, network: 0s)
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0002, network: 0.0001s)
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0001, network: 0s)
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0003, network: 0.0001s)
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0002, network: 0s)
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0002, network: 0.0001s)
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0002, network: 0s)
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0002, network: 0.0001s)
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0006, network: 0s)
-> NET_SSH2_MSG_CHANNEL_OPEN (since last: 0.0001, network: 0s)
<- NET_SSH2_MSG_CHANNEL_OPEN_FAILURE (since last: 0.0103, network: 0s)
-> NET_SSH2_MSG_DISCONNECT (since last: 0.0003, network: 0s)

**Comment by terrafrost** [comment] 2016-10-11 15:30
The detailed logs would be more helpful. Especially since there's apparently not too many packets being sent before you're getting the error. You can get the detailed logs by doing `define('NET_SSH2_LOGGING', 2);` at the top of the file.

That said, doing `terminal length 0` with write() and then `show running-config | begin !` with exec() isn't the same thing as doing `terminal length 0` and `show running-config | begin !`. SSH uses channels. Interactive prompt's are one channel and one-off commands are done on a channel dedicated for them that self destructs after the command has been ran. Stuff done on one channel doesn't have an effect on stuff done on another channel. This is why doing `$ssh->exec('cd /'); echo $ssh->exec('pwd');` doesn't always yield the expected behavior.

I mean, I guess that's a bit of an oversimplification. If you do `shutdown` in one channel that'll affect all channels. I suppose `terminal length 0` could be global like `shutdown` but I wouldn't count on it.. 
it's possible Cisco does

**Comment by thadin** [comment] 2016-10-11 16:06
I need an interactive session, so maybe the dedicated channels that come with `exec` may not be for me.

I'm currently using a custom class which extends the SSH2 class and handles the write/read commands for me.

Below is a log with `define('NET_SSH2_LOGGING', 2);` in case you want to debug it for other users.

[detailed-log.txt](https://github.com/phpseclib/phpseclib/files/522344/detailed-log.txt)

**Comment by Bebrazmogis** [comment] 2016-12-12 14:25
I have the same issue.

Code 
```$this->ssh = new SSH2($server->ip);
$success = $this->ssh->login('root', $server->password);   
$this->ssh->enablePTY();
$distro = $this->getDistro();
$os = $this->getOs();

private function getDistro()
{
    $output = trim($this->ssh->exec("cat /etc/*-release | grep ^NAME="));
    return ($index = strpos($output, "=")) !== false ? trim(substr($output, $index+2, -1)) : $output;
}

private function getOs() 
{
    return trim($this->ssh->exec("uname -o"));
}
```

Partial stack trace:
```
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(1024, 'Unable to open ...', '/mnt/c/GitHub/s...', 3273, Array)
#1 /mnt/c/GitHub/server-host/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3273): user_error('Unable to open ...')
#2 /mnt/c/GitHub/server-host/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2421): phpseclib\Net\SSH2->_get_channel_packet(0)
#3 /mnt/c/GitHub/server-host/app/Listeners/ServerSetUp.php(86): phpseclib\Net\SSH2->exec('uname -o')
#4 /mnt/c/GitHub/server-host/app/Listeners/ServerSetUp.php(46): App\Listeners\ServerSetUp->getOs()
```
Detailed log: http://pastebin.com/2EGWmCL2

PHP version
```
PHP 7.0.13-1+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.13-1+deb.sury.org~trusty+1, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by terrafrost** [comment] 2016-12-15 17:26
The problem is that you've enabled a PTY. Once you've done that exec() works like an interactive shell in that you have to do `read()` to get output and can send data in the middle of receiving the output via `write()`.

A normal `exec()` command dies after the output has ended. But with a PTY that's not the case because the command doesn't necessarily have to die. ie. if you did `$ssh->exec('bash')` with a PTY...  that command wouldn't really die unless you did `$ssh->exec("exit\n")` whist not being in vim or some such.

Your code has you parsing the output of `$ssh->exec()` even tho you have a PTY. That doesn't work. Example:

```php
$ssh->enablePTY();

echo $ssh->exec('ls -latr');
```
That returns 1 because `$ssh->exec()` returned true.

A few more code snippets:

```php
$ssh->enablePTY();
echo $ssh->exec('ls -latr');
echo $ssh->exec('pwd');
```
That gives me an error similar to the one you're getting. Since phpseclib 1.0 / 2.0 have a fixed channel for exec's you can't do two exec's with a PTY concurrently so the above will never really work but maybe I can make it so that instead of outputting an error the second `$ssh->exec()` returns false. (fwiw, I do plan on supporting dynamic channels in the master / 3.0 version at some point).

Also...

```php
$ssh->enablePTY();
echo $ssh->exec('ls -latr');
$ssh->disablePTY();
echo $ssh->exec('pwd');
```

Without a PTY exec() would close the channel after it got the output. But with a PTY it doesn't do that and `$ssh->disablePTY()` doesn't close the channel either. It'd probably be good if it did but it doesn't. I'll look into changing that behavior.

**Comment by terrafrost** [comment] 2016-12-17 22:12
https://github.com/phpseclib/phpseclib/pull/1075 should make this work better.

**Comment by terrafrost** [comment] 2016-12-25 05:33
#1075 has been merged.

As for the other two people who posted in this topic...  lukepolo's code doesn't show a PTY being used but the fact that he's doing `read()` after `exec()` makes it seem like he very well could be. thadin doesn't appear to be using a PTY but he might get the desired behavior if he were.

**Comment by terrafrost** [comment] 2016-12-25 05:33
I'm going to go ahead and close this. If this is still an issue for people they should create a new issue.

**Closed by terrafrost** 2016-12-25 05:33 UTC

**Comment by chrisnew** [comment] 2017-05-04 08:48
Any plans when this fix will be released?

**Comment by terrafrost** [comment] 2017-05-05 12:56
I'll try to do a release this weekend.

Thanks!

**Comment by terrafrost** [comment] 2017-05-08 06:03
A new release has been made.

Thanks!

**Comment by CaptainConner** [comment] 2017-05-28 08:24
Eventhough I have installed the latest patch, which should fix this, it appears to not be working as you can see here: https://gyazo.com/430818f39ac0bfab69b44904b6b294da

I am running multiple exec's, and the connections appear to be staying open as long as my script is running.

**Comment by CaptainConner** [comment] 2017-05-28 14:18
My code basically uses the exec() function every 3 seconds for about a minute if a file on the server has changed. I am having the exact same issue, most of the time the script works, but sometimes it will come up with the "Unable to open channel" error.

The interface shown is the Windows Bitvise SSH Server connection logger - it shows open connections. You said that after an exec is issued, it should now close the open connection, it does not appear to be doing so, as the connections only disappear when the script finishes executing.

**Comment by terrafrost** [comment] 2017-05-28 15:02
So this post has had like 15 different people reporting the issue. Only a very small subset of people reporting this issue have actually provided enough information with which diagnostics can be made.

It is not clear whether or not everyone experiencing this issue is experiencing it for the same reasons. There may be a multitude of reasons why people are getting this error and if so the change I made might very well only fix one of root causes of the error.

Anyway, I just mention that because I think it'd be beneficial if you made a new post instead of replying to an existing one. What I've already said not withstanding a new post is also less likely to be lost.

Regardless...  seeing some code would still be very helpful. #1075 fixes an issue with PTYs. Or at least provides a way to work around PTY issues. Are you using a PTY?

Issuing a command every 3s isn't, in and of itself, a problem. Example with the following Vagrant box:

```
Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/trusty64"
end
```

PHP code:

```
$ssh = new SSH2('127.0.0.1', 2200);
$ssh->login('vagrant', 'vagrant');

for ($i = 0; $i < 60 / 3; $i++) {
	$ssh->exec('ls -latr');
}
```

That works fine.

By default `exec()` will block until it has all the output and the channel is closed so you're probably doing something else. As such code and logs will be very helpful.

Thanks!

**Comment by hekep** [comment] 2017-07-12 13:50
I still get this error message.

My workaround was to create new SSH2 instance (and ->login() and ->disconnect() )  for each  command execution.

**Comment by terrafrost** [comment] 2017-07-12 16:33
> I still get this error message.

You make it sound as tho you've posted before in this ticket - you haven't.

Quoting my last post:

> So this post has had like 15 different people reporting the issue. Only a very small subset of people reporting this issue have actually provided enough information with which diagnostics can be made.
>
> It is not clear whether or not everyone experiencing this issue is experiencing it for the same reasons. There may be a multitude of reasons why people are getting this error and if so the change I made might very well only fix one of root causes of the error.
>
> Anyway, I just mention that because I think it'd be beneficial if you made a new post instead of replying to an existing one. What I've already said not withstanding a new post is also less likely to be lost.
>
> Regardless... seeing some code would still be very helpful. #1075 fixes an issue with PTYs. Or at least provides a way to work around PTY issues. Are you using a PTY?

In light of the fact that people keep on posting replies to this instead of creating new tickets I am going to lock this ticket. If people are seeing this error message they'll need to make a new post.
