### ISSUE TITLE
getting error while encrypt file size 7gb

### ISSUE THREAD

**Issue by ifba** [phpseclib/phpseclib#1021] opened 2016-08-05 10:15 UTC
i try to encrypt file size 7gb, but getting this error
[Fri Aug 05 17:47:58.665319 2016] [:error] [pid 12529] [client 192.168.0.127:53717] PHP Fatal error:  String size overflow in

**Comment by terrafrost** [comment] 2016-08-05 15:52
7GB is pretty big for a string. Maybe try to encrypt it piece meal with continuous mode. eg.

```php
$aes->enableContinuousMode();
while (!feof($input)) {
    fwrite($output, $aes->encrypt(fread($input, 1024)));
}
```

**Comment by bantu** [comment] 2016-10-22 12:38
I am closing this. This is very very likely simply caused by attempting to create a 7 GiB string.

**Closed by bantu** 2016-10-22 12:38 UTC
Labels: support
