### ISSUE TITLE
Issue retrieving a file using sftp, strange NET_SSH2_MSG_CHANNEL_DATA packet

### ISSUE THREAD

**Issue by Stevehans** [phpseclib/phpseclib#1421] opened 2019-10-17 12:44 UTC
I've a reproducible issue, when retrieving a large file from a Go Anywhere sftp server, I suddenly stop receiving file data and start receiving these packets, any idea what they are?

I'm using 2.0.23 
Last good data packet (seems to stop short as the previous ones have all been 16k in size)
<pre>
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.6684, network: 0s)
00000000  00:00:01:00:00:00:00:1f:32:2e:31:30:2c:20:20:20  ........2.10,
00000010  20:20:20:20:20:20:20:20:20:20:2e:30:30:2c:20:20            .00,
00000020  20:20:20:20:20:20:20
</pre>

Followed by numerous of the following:-
<pre>
-> NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0003, network: 0s)
00000000  00:00:00:00:00:00:00:3d:00:00:00:39:05:00:00:00  .......=...9....
00000010  00:00:00:00:24:62:37:37:36:38:61:37:39:2d:61:39  ....$b7768a79-a9
00000020  34:63:2d:34:61:36:32:2d:62:36:39:63:2d:33:65:63  4c-4a62-b69c-3ec
00000030  39:38:35:37:36:64:31:64:36:00:00:00:00:7f:f0:00  98576d1d6.......
00000040  00:00:00:80:00                                   .....

-> NET_SFTP_READ (0.0001s)
00000000  00:00:00:24:66:37:39:37:62:39:34:38:2d:32:31:38  ...$f797b948-218
00000010  33:2d:34:37:31:39:2d:62:61:37:61:2d:30:34:38:65  3-4719-ba7a-048e
00000020  34:65:38:33:31:36:64:35:00:00:00:00:7f:f0:00:00  4e8316d5........
00000030  00:00:80:00                                      ....

-> NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0002, network: 0s)
00000000  00:00:00:00:00:00:00:3d:00:00:00:39:05:00:00:00  .......=...9....
00000010  01:00:00:00:24:62:37:37:36:38:61:37:39:2d:61:39  ....$b7768a79-a9
00000020  34:63:2d:34:61:36:32:2d:62:36:39:63:2d:33:65:63  4c-4a62-b69c-3ec
00000030  39:38:35:37:36:64:31:64:36:00:00:00:00:7f:f0:80  98576d1d6.......
00000040  00:00:00:80:00                                   .....

-> NET_SFTP_READ (0s)
00000000  00:00:00:24:66:37:39:37:62:39:34:38:2d:32:31:38  ...$f797b948-218
00000010  33:2d:34:37:31:39:2d:62:61:37:61:2d:30:34:38:65  3-4719-ba7a-048e
00000020  34:65:38:33:31:36:64:35:00:00:00:00:7f:f0:80:00  4e8316d5........
00000030  00:00:80:00                                      ....

</pre>

In the above the SSH2 logging is from a different session than the SFTP logging (hence what look like GUIDs being different), but it demonstrates the issue.

**Comment by Stevehans** [comment] 2019-10-17 12:52
I've just noticed the direction, this is being sent to the remote server, not received from it?

**Comment by Stevehans** [comment] 2019-10-17 13:08
Ok, the guid is the handle and this looks to be our acks back to the remote server?

Eventually the transfer dies with PHP Notice:  Expected SSH_FX_DATA or SSH_FXP_STATUS

**Comment by terrafrost** [comment] 2019-10-18 05:10
I'd have to see more of the packet logs. SFTP packets can span multiple SSH2 packets and the incoming packet seems to be a portion of a larger packet.

As for the outgoing packets...  phpseclib sends 32x (or whatever NET_SFTP_QUEUE_SIZE is set to) SSH_FXP_READ packets at a time and in anticipation of 32x SSH_FXP_DATA packets (or an SSH_FXP_STATUS packet). That's why you're seeing a bunch of outgoing packets.

I do wonder if doing `define('NET_SFTP_QUEUE_SIZE', 1)` would help but, short of that...  I am curious about what type of packet you _are_ getting. Or maybe you're not getting one at all and it's timing out?

Would you be able to provide me with credentials to connect to the server? You could email them to terrafrost@php.net. Failing that maybe I can try to install https://www.goanywhere.com/customer-portal-trial-registration and see if I can reproduce the issue. I have a busy weekend this weekend and will be in Washington, DC for most of next week and setting up their software is gonna take more time than just connecting to an already setup setup. And anything that makes it take less time for me to diagnose is definitely a good thing in my books lol

**Comment by Stevehans** [comment] 2019-10-18 08:03
I'm out of ideas.
For a get, assuming that there is no size specified, we make NET_SFTP_QUEUE_SIZE requests for data and then loop through the responses for these, either saving the data or clearing down the response queue.

In my case, regardless of what I set the queue size to, the other end seems to stop responding after a set amount of data

**Comment by Stevehans** [comment] 2019-10-18 08:06
Sorry, that was an unsent comment from last night!

It's not really viable to test with my server as it requires a file of 2GB+ and that would take 20+ mins as I've tested from home, so you really want to run it locally.

I've tried with the queue size set to 16, I'll set it to 1.

I'll also put in a pull request as I've tidied up the logging to get rid of various errors.

An attempt to retrieve the whole file stops at the same point each time, however, retrieving the last chunk using an offset, even an offset moved back 0.5G will work fine.

**Comment by Stevehans** [comment] 2019-10-18 08:19
Tried with queue length defined as 1 and still fails at the same size.

**Comment by terrafrost** [comment] 2019-10-18 13:03
So one thing that might help me, too, is if you enable real time logging to a file, which can be done by doing `define('NET_SSH2_LOGGING', 4); define('NET_SSH2_LOG_REALTIME_FILENAME', '/path/to/filename.ext');` at the top. The log size will be 1MB, by default, unless you change it with `LOG_MAX_SIZE`.

> It's not really viable to test with my server as it requires a file of 2GB+ and that would take 20+ mins as I've tested from home, so you really want to run it locally.

I'll endevour to do that.

Thanks!

**Comment by Stevehans** [comment] 2019-10-18 18:29
I'll do that Sunday as soon as I return.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by Stevehans** [comment] 2019-10-21 09:06
Ok, done, I've redacted the data, the logging looks a little strange and there was a bug in SSH2.php in that it was trying to use a class constant rather than the intended define (line 4000)

**Comment by Stevehans** [comment] 2019-10-21 09:07
[sftp.txt](https://github.com/phpseclib/phpseclib/files/3749890/sftp.txt)

**Comment by terrafrost** [comment] 2019-10-23 10:34
I just tried to download a 1.84GB file with Go Anywhere SFTP server and was able to do so without issue. After the download I did `md5_file()` on the newly downloaded file and the original and got the same result for both.

One thing I do note with the logs you posted is this:

```
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0124, network: 0s)
00000000  00:00:01:00:00:00:00:1f:nn:nn:nn:nn:nn:nn:nn:nn  ........xxxxxxxx
00000010  nn:nn:nn:nn:nn:nn:nn:nn:nn:nn:nn:nn:nn:nn:nn:nn  xxxxxxxxxxxxxxxx
00000020  nn:nn:nn:nn:nn:nn:nn                             xxxxxxx

<- NET_SSH2_MSG_IGNORE (since last: 30.8418, network: 0.0001s)
00000000  00:00:00:21:9c:08:80:f3:f8:ad:2d:6f:0d:8d:b0:d0  ...!......-o....
00000010  1b:1b:b1:55:78:4c:0c:5d:3c:df:f9:cc:74:89:01:5f  ...UxL.]....t.._
00000020  d9:82:68:b1:75                                   ..h.u

<- NET_SSH2_MSG_DISCONNECT (since last: 28.305, network: 28.3049s)
00000000  00:00:00:0b:00:00:00:21:53:65:6e:64:69:6e:67:20  .......!Sending 
00000010  6f:66:20:63:68:61:6e:6e:65:6c:20:64:61:74:61:20  of channel data 
00000020  74:69:6d:65:64:20:6f:75:74:00:00:00:00           timed out....
```

I guess what I'd do is...  I'd get the "simple" SSH2 logs (`define('NET_SSH2_LOGGING', 1);`) and I'd get a list of the SSH2 errors (`$sftp->getErrors()`) and SFTP errors (`$sftp->getSFTPErrors()`). Post them here, let's see what those reveal, and then if I still can't figure anything out I'll make a post on https://www.goanywhere.com/forum/

**Comment by Stevehans** [comment] 2019-10-23 10:44
The issue only seems to happen on files 2GB+

I’ll add that logging and post the log.

**Comment by Stevehans** [comment] 2019-10-23 11:56
This is the result of the run with error dumps at the end:-
PHP Notice:  Expected SSH_FX_DATA or SSH_FXP_STATUS in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php on line 2273
PHP Notice:  Expected SSH_FX_DATA or SSH_FXP_STATUS in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php on line 2273
PHP Notice:  Expected SSH_FX_DATA or SSH_FXP_STATUS in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php on line 2273
PHP Notice:  Connection closed by server in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3672
PHP Notice:  Expected SSH_FX_DATA or SSH_FXP_STATUS in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php on line 2273
PHP Notice:  Connection closed prematurely in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3294
PHP Notice:  Connection closed by server in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3672
PHP Notice:  Expected SSH_FX_DATA or SSH_FXP_STATUS in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php on line 2273
PHP Notice:  Connection closed prematurely in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3294
PHP Notice:  Connection closed by server in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3672
PHP Notice:  Expected SSH_FX_DATA or SSH_FXP_STATUS in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php on line 2273
PHP Notice:  Connection closed prematurely in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3294
PHP Notice:  Connection closed by server in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3672
PHP Notice:  Expected SSH_FX_DATA or SSH_FXP_STATUS in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php on line 2273
PHP Notice:  Connection closed prematurely in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3294
PHP Notice:  Connection closed by server in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3672
PHP Notice:  Expected SSH_FX_DATA or SSH_FXP_STATUS in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php on line 2273
PHP Notice:  Connection closed prematurely in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3294
PHP Notice:  Connection closed by server in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3672
PHP Notice:  Expected SSH_FX_DATA or SSH_FXP_STATUS in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php on line 2273
PHP Notice:  Connection closed prematurely in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3294
PHP Notice:  Connection closed by server in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3672
PHP Notice:  Expected SSH_FX_DATA or SSH_FXP_STATUS in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php on line 2273
PHP Notice:  Connection closed prematurely in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3294
PHP Notice:  Connection closed by server in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3672
PHP Notice:  Expected SSH_FX_DATA or SSH_FXP_STATUS in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php on line 2273
PHP Notice:  Connection closed prematurely in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3294
PHP Notice:  Connection closed by server in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3672
PHP Notice:  Expected SSH_FX_DATA or SSH_FXP_STATUS in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php on line 2273
PHP Notice:  Connection closed prematurely in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3294
PHP Notice:  Connection closed by server in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3672
PHP Notice:  Expected SSH_FX_DATA or SSH_FXP_STATUS in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php on line 2273
PHP Notice:  Connection closed prematurely in /var/www/html/wr98test/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3903
SFTP Error(s):
SSH2 Error(s): SSH_MSG_DISCONNECT: NET_SSH2_DISCONNECT_BY_APPLICATION
Sending of channel data timed out
SFTP Connected: false
SFTP Authenticated: false
SFTP Timed Out: true

**Comment by Stevehans** [comment] 2019-10-23 12:52
[ssh2 simple log.txt](https://github.com/phpseclib/phpseclib/files/3762430/ssh2.simple.log.txt)

Window size adjustment just before it does?

**Comment by Stevehans** [comment] 2019-10-23 12:57
Found this comment in SSH2.php

// RFC4254 defines the (client) window size as "bytes the other party can send before it must wait for the window to
// be adjusted".  0x7FFFFFFF is, at 2GB, the max size.  technically, it should probably be decremented, but,
// honestly, if you're transferring more than 2GB, you probably shouldn't be using phpseclib, anyway.
// see http://tools.ietf.org/html/rfc4254#section-5.2 for more info

**Comment by terrafrost** [comment] 2019-10-23 18:10
> Window size adjustment just before it does?

Maybe but tbh I suspect the issue is more likely to be with GoAnywhere.

phpseclib had window sizing issues in days of yore but it hasn't had a confirmed issue in years. Examples of old instances of window sizing:

https://github.com/phpseclib/phpseclib/commit/c0555581e755b68d0d2019a5fb2a7b15f2fff50a#diff-82a5983a6daace4acbcc65edf2dfb605
https://github.com/phpseclib/phpseclib/commit/9e71e0bce87d56b9ef80ddb12947ae84bb9b5c26#diff-82a5983a6daace4acbcc65edf2dfb605
https://github.com/phpseclib/phpseclib/commit/db32efb2767b4b265dad85bc12567fea5e4ff623#diff-82a5983a6daace4acbcc65edf2dfb605

etc.

I'll try to examine this in more depth this evening but I suspect phpseclib's SFTP code is more vetted then GoAnywhere's SFTP code.

Maybe the issue actually is with phpseclib but one shouldn't assume that the issue is with phpseclib just because it's in PHP. Example:

https://github.com/PowerShell/Win32-OpenSSH/issues/48

The issue was reported as a phpseclib issue but it actually wasn't.

Anyway, like I said, I'll try to take a look when I get home this evening.

Thanks!

**Comment by terrafrost** [comment] 2019-10-24 15:27
So as an update I am able to reproduce this with a 3GB file. I'm trying to take a look at this as time permits but I'm currently at a conference in DC, will be doing sight seeing on Friday and Saturday, in DC, and will then be flying back to my hometown on Sunday. Back at work on M-F so it's tricky finding the time atm.

**Comment by terrafrost** [comment] 2019-10-25 02:01
This seems to work as a workaround:

```php
class SFTP2 extends SFTP { var $window_size = 1024 * 1024; }
```
(just instantiate SFTP2 instead of SFTP!)

**Comment by Stevehans** [comment] 2019-10-25 13:16
That fixes it for me too, many thanks for your work on this, it really is appreciated.

Do you think this is an issue with phpseclib  or more likely to be with the Go Anywhere server?

**Comment by terrafrost** [comment] 2019-10-26 10:07
Based on what I'm seeing right now I'm currently leaning towards this being a phpseclib bug since I'm able to download a 3GB file from GoAnywhere's SFTP server without issue.

One problem with testing this is the file size. Is this an issue with uploading or just downloading files? I can't upload a 3GB file on my Windows 10 laptop due to some weird PHP issues. In particular, even though `PHP_INT_SIZE` is returning 8 (indicating that it uses 64-bit signed integers) `fstat`, `stat`, `filesize`, etc, all return the file size as 2GB, when uploading with something like `$sftp->put('remote.file', 'local.file', SFTP::SOURCE_LOCAL_FILE);`. 2GB is 0x7FFF FFFF, which is the max signed 32-bit integer you have. So it's like `filesize` is returning 32-bit signed ints even on a system that supports 64-bit signed ints.

Maybe this wouldn't be an issue on Linux? Maybe this isn't an issue on PHP 7.3? Maybe I could write a new `put()` method that uploads until `feof` returns false instead of until when the number of uploaded bytes is equal to the file size but would `fread` even work past 2GB? idk.

Something else I want to try too: can I reproduce the issue on OpenSSH? I'm using a trial version of GoAnywhere. That trial version is going to expire soon and since I'm not doing this for profit I'm going to spend money to purchase it (unless you want to purchase it for me lol but even if you'd be willing let's hold off until we can see if I'm able to reproduce this on OpenSSH).

Unfortunately, this is all slow going. I logged PuTTY's SSH packets but that produced a 15GB log. I can't easily open that up with just any text editor so I've been using `grep` and `sed` to analyze it. Further complicating matters is the fact that, right now, my schedule is just...  busy. If today was a normal weekend I might be able to devote two full days to this. But this is not a normal weekend. I'm in Washington, DC doing touristy stuff and I want to make the most of my time here. Next weekend will be my last weekend in the US before I head off to Egypt and Turkey for more tourism (I'll be gone for the rest of the month of November). Spending lots of time on this during the weekdays isn't viable because I have an 8-5 job that sucks up most of my time during the weekdays. So I'm trying to make progress but it's not gonna be as fast as might be desired, unfortunately :(

**Comment by terrafrost** [comment] 2019-10-26 10:09
> since I'm able to download a 3GB file from GoAnywhere's SFTP server without issue

...with PuTTY's psftp. I'm able to download a 3GB file without issue _with PuTTY's psftp_. Left that bit out of my original post lol

**Comment by terrafrost** [comment] 2019-10-29 03:42
So as an update...   this issue is not reproducable in OpenSSH with 3GB files.

As for GoAnywhere..  in SSH2.php there's this:

                    $packet = pack('CNN', NET_SSH2_MSG_CHANNEL_WINDOW_ADJUST, $this->server_channels[$channel], $this->window_size);
                    $this->send_binary_packet($packet);
                    $this->window_size_server_to_client[$channel]+= $this->window_size;

In my testing, replacing `$this->window_size` (which is 0x7FFF FFFF) with `500000` fixes the issue.

That this work is inspired by the fact that altho PuTTY's initial windows size matches phpseclib's (0x7FFF FFFF) the window resize packets just set it to ~500000. I need to get a better grasp on why PuTTY is setting the window resize packets to that. Is it doing it for just GoAnywhere or is it doing it for OpenSSH as well? All things to figure out ...

**Comment by terrafrost** [comment] 2019-11-02 20:01
https://github.com/phpseclib/phpseclib/commit/a4ed6b80f3676bf3a712af6d89e8f465f4b27747 should fix the issue!

So PuTTY was sending SSH2_MSG_CHANNEL_WINDOW_ADJUST packets, resizing by around 0x40000000 vs the 0x7FFFFFFF that phpseclib was doing:

```
Outgoing packet #0xb535, type 2 / 0x02 (SSH2_MSG_IGNORE)
  00000000  00 00 00 00                                      ....
Outgoing packet #0xb536, type 98 / 0x62 (SSH2_MSG_CHANNEL_REQUEST)
  00000000  00 00 00 00 00 00 00 22 77 69 6e 61 64 6a 40 70  ......."winadj@p
  00000010  75 74 74 79 2e 70 72 6f 6a 65 63 74 73 2e 74 61  utty.projects.ta
  00000020  72 74 61 72 75 73 2e 6f 72 67 01                 rtarus.org.
Outgoing packet #0xb537, type 93 / 0x5d (SSH2_MSG_CHANNEL_WINDOW_ADJUST)
  00000000  00 00 00 00 40 00 01 37                          ....@..7
```

So in PuTTY's [ssh.c](https://github.com/github/putty/blob/master/ssh.c) there's this:

```c
static void ssh2_msg_channel_data(Ssh ssh, struct Packet *pktin)
{
...
	bufsize = ssh_channel_data(c, ext_type == SSH2_EXTENDED_DATA_STDERR,
				   data, length);
...
	/*
	 * If we are not buffering too much data,
	 * enlarge the window again at the remote side.
	 * If we are buffering too much, we may still
	 * need to adjust the window if the server's
	 * sent excess data.
	 */
	if (bufsize < c->v.v2.locmaxwin)
	    ssh2_set_window(c, c->v.v2.locmaxwin - bufsize);
```

If you trace through the code you'll see that bufsize is pretty much always 0 (`ssh_channel_data` calls `from_backend`, defined in [windows/window.c](https://github.com/github/putty/blob/master/windows/window.c), which in turn, calls `term_data`, defined in [terminal.c](https://github.com/github/putty/blob/master/terminal.c), which returns 0).

`c->v.v2.locmaxwin` is set to 0x7FFFFFFF in `ssh_channel_init` in ssh.c (well, it's set to `OUR_V2_BIGWIN` if `ssh_is_simple()` returns true, which in our case, it does).

So what we have is `ssh2_set_window(c, 0x7FFFFFFFF)` being called on pretty much every packet.

As for `ssh2_set_window`...

```c
static void ssh2_set_window(struct ssh_channel *c, int newwin)
{
...

    /*
     * Only send a WINDOW_ADJUST if there's significantly more window
     * available than the other end thinks there is.  This saves us
     * sending a WINDOW_ADJUST for every character in a shell session.
     *
     * "Significant" is arbitrarily defined as half the window size.
     */
    if (newwin / 2 >= c->v.v2.locwindow) {

	pktout = ssh2_pkt_init(SSH2_MSG_CHANNEL_WINDOW_ADJUST);
	ssh2_pkt_adduint32(pktout, c->remoteid);
	ssh2_pkt_adduint32(pktout, newwin - c->v.v2.locwindow);
	ssh2_pkt_send(ssh, pktout);
	c->v.v2.locwindow = newwin;
```
So since `newwin` is always pretty much 0x7FFFFFFF dividing it by two will pretty much always yield 0x3FFFFFFF. `c->v.v2.locwindow` is incremented every time a data packet is sent out. It always starts at 0x7FFFFFFF (`OUR_V2_BIGWIN`) so it's basically resizing whenever the window size gets less than 0x3FFFFFFF.

idk what PuTTY is talking about when it says "_this saves us sending a WINDOW_ADJUST for every character in a shell session_" but maybe PuTTY uses different window sizes for shell sessions than it does for SFTP idk lol

My personal take is that this is a bug with GoAnywhere but unless I can find another SFTP client other than phpseclib that reproduces the issue I'm somewhat disinclined to report the bug. And tbh idk that I care enough to do an exhaustive search of every SFTP client under the sun to find one for which GoAnywere craps out when attempting to download a 3GB file.

**Comment by Stevehans** [comment] 2019-11-12 17:56
Thanks for all your efforts on this, it's much appreciated.

**Closed** 2019-11-13 00:35 UTC

**Comment by Stevehans** [comment] 2019-12-03 09:40
Presume this will be in 2.0.24 when pushed to composer?

**Comment by terrafrost** [comment] 2019-12-03 10:22
Yup!
