### ISSUE TITLE
PublicKeyLoader leaking memory on SFTP login

### ISSUE THREAD

**Issue by DRoet** [phpseclib/phpseclib#1686] opened 2021-08-04 09:32 UTC
I was still experiencing some memory issues after https://github.com/phpseclib/phpseclib/issues/1672#issuecomment-877684439 and using `gc_collect_cycles()`

I managed to track it down to `PublicKeyLoader`, it seems to increase the memory pretty much every cycle. Using a regular username/password doesn't have this problem.

Example (using 3.0.x-dev, private_key.pem being an RSA private key):
```php
<?php

use phpseclib3\Crypt\PublicKeyLoader;
use phpseclib3\Net\SFTP;

require_once('../vendor/autoload.php');

while (true) {
   $sftp = new SFTP('hostname');
   $login = $sftp->login('username', PublicKeyLoader::load(file_get_contents('private_key.pem'), 'password'));
   echo memory_get_usage() . "\n";
   sleep(1);
}
```

**Comment by terrafrost** [comment] 2021-08-14 18:58
Sorry for the delay - had a super busy week.

Anyway, I'm not having any issues myself:

```php
<?php
require __DIR__ . '/vendor/autoload.php';

use phpseclib3\Crypt\PublicKeyLoader;
use phpseclib3\Net\SFTP;

//define('NET_SSH2_LOGGING', 3);

while (true) {
    $sftp = new SFTP('website.com');
    if (!$sftp->login('root', PublicKeyLoader::load(file_get_contents('/path/to/key.pem')))) {
        exit('bad login');
    }

    gc_collect_cycles();
    $new = memory_get_usage();
    if (isset($old)) {
        echo ($new - $old) . "\n";
    }
    $old = $new;
}
```
The memory usage was not increasing.

Maybe it has something to do with the algorithms that have been negotiated. Maybe you could do `print_r($sftp->getAlgorithmsNegotiated())` and tell me what that says?

Here's what mine gives me:

```
Array
(
    [kex] => curve25519-sha256@libssh.org
    [hostkey] => ssh-ed25519
    [client_to_server] => Array
        (
            [crypt] => aes128-gcm@openssh.com
            [mac] => hmac-sha2-256-etm@openssh.com
            [comp] => none
        )

    [server_to_client] => Array
        (
            [crypt] => aes128-gcm@openssh.com
            [mac] => hmac-sha2-256-etm@openssh.com
            [comp] => none
        )

)
```

**Comment by terrafrost** [comment] 2021-08-14 19:01
I tried to switch the BigInteger engine up by doing `BigInteger::setEngine('BCMath');` and `BigInteger::setEngine('PHP64');` and was able to get some memory leaks that way.

**Comment by terrafrost** [comment] 2021-08-14 22:45
So idk if this explains all of the memory leaks but I get a memory leak with this code:

```php
<?php
while (true) {
    eval('return function() {};');
    gc_collect_cycles();
    $new = memory_get_usage();
    if (isset($old)) {
        echo ($new - $old) . "\n";
    }
    $old = $new;
}
```

The issue is with the `eval()` and I think this is a PHP bug. https://bugs.php.net/80199 is basically the same issue. nikic@php.net closed that bug report as a dupe of https://bugs.php.net/76982 . Quoting their most recent response in https://bugs.php.net/76982 : 

> This leak is partially fixed in PHP 8.1. There's still a memory leak, but it's a constant leak of ~250 bytes per overwritten closure now.

Superficially one might think that not using `eval()` would do the trick BUT to achieve a lot of the speedups that phpseclib is able to get `eval()` is needed. https://github.com/phpseclib/phpseclib/issues/1293 and https://github.com/phpseclib/phpseclib/pull/1143 discuss why it's needed.

Quoting https://www.reddit.com/r/PHP/comments/9mfetd/the_land_where_php_uses_eval/e7fesdw/ SaraMG (pollita@php.net):

> I'm going to hold onto this library as a benchmark for engine work and as the first arguably legitimate use of eval I've ever seen in almost 20 years of using this language.

**Comment by terrafrost** [comment] 2021-08-15 00:45
One way to significantly reduce the memory leak would be to use the GMP extension. If you're using the PHP64 BigInteger engine you could also do this:

```php
BigInteger::setEngine('PHP64', ['Reductions\Barrett']);
```
I was gonna say that using that reduction mode vs `Reductions\EvalBarrett` would result in a big slowdown BUT I guess in the context of SSH the biggest bottleneck is most likely not PHP but rather the network itself.

**Comment by DRoet** [comment] 2021-08-16 08:02
Output from `print_r($sftp->getAlgorithmsNegotiated())` on my end is exactly the same as yours. 

Using the GMP extension indeed seems to slow down the memory leak and so does `BigInteger::setEngine('PHP64', ['Reductions\Barrett'])`, although still faster then using GMP.

I am curious though, you said you didn't see any increase in your example (https://github.com/phpseclib/phpseclib/issues/1686#issuecomment-898945443). I tested that example on both Linux/Windows with the extensions enabled/disabled but I am still seeing the initial problem.

On a side note, V2 didn't have this same problem for me, has this functionality become significantly different between the two versions?

**Comment by terrafrost** [comment] 2021-08-16 13:51
> I am curious though, you said you didn't see any increase in your example (#1686 (comment)). I tested that example on both Linux/Windows with the extensions enabled/disabled but I am still seeing the initial problem.

I tried it with the GMP extension but it's possible I still had some debug code from my trying to track down memory leaks from the last time I looked into them. Whatever debug code was in place was removed when I did a `git reset --hard origin/3.0`. I can try to rerun the benchmark again at some point

> On a side note, V2 didn't have this same problem for me, has this functionality become significantly different between the two versions?

V3 supports a lot more algorithms than V2 did. Current best practices dictates elliptic curves be used and V2 had absolutely no EC curve support.

**Closed** 2022-02-27 17:38 UTC
