### ISSUE TITLE
MCRYPT ext. deprecated in PHP 7.1.x and will be removed in PHP 7.2.x

### ISSUE THREAD

**Issue by nuxwin** [phpseclib/phpseclib#1067] opened 2016-12-02 21:59 UTC
See the title. It is maybe time to switch to openssl to avoid any suprise.

See also https://wiki.php.net/rfc/mcrypt-viking-funeral

Thank you.

**Comment by terrafrost** [comment] 2016-12-02 22:06
Duplicate of #1028. See, also, #1040.

**Comment by nuxwin** [comment] 2016-12-09 04:51
@terrafrost 

Sorry for the duplicate report... Next time, I'll look better ;)

**Comment by terrafrost** [comment] 2016-12-10 07:48
No worries! I'd rather have a dupe report than no report at all lol

**Closed by terrafrost** 2016-12-10 07:48 UTC
