### ISSUE TITLE
[Enhancement] mode GCM

### ISSUE THREAD

**Issue by piotrgolasz** [phpseclib/phpseclib#972] opened 2016-04-18 12:49 UTC
@terrafrost would it be burdensome to code GCM mode (Galois Counter Mode)?
afaik openssl already supports it, reason for implementation is to prevent lucky13 attack

**Comment by terrafrost** [comment] 2016-04-18 20:20
I'm not sure - I'll have to look into it. I'll do so at some point and get back to you.

**Comment by bantu** [comment] 2016-04-19 05:42
I am closing this as a duplicate of #47 if you don't mind.

**Closed by bantu** 2016-04-19 05:42 UTC
