### ISSUE TITLE
Undefined offset: 256 in ..../vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:420

### ISSUE THREAD

**Issue by lukepolo** [phpseclib/phpseclib#1014] opened 2016-07-25 14:32 UTC
Not sure whats really happening , hoping for a quick fix! 

`$this->server_channels[self::CHANNEL],
`

![screen shot 2016-07-25 at 10 30 35 am](https://cloud.githubusercontent.com/assets/2066668/17104912/f0c626b8-5252-11e6-8355-fd15818ee1a6.png)

**Comment by terrafrost** [comment] 2016-07-25 18:11
Normally, `$response = $this->_get_channel_packet(self::CHANNEL);` populates `$this->server_channels[self::CHANNEL],`. It's weird that it isn't for you. Can you post your server logs? You can get them by doing `define('NET_SSH2_LOGGING', 2);` at the top and `echo $ssh->getLog();` after the failed login attempt.

Thanks!

**Comment by lukepolo** [comment] 2016-07-25 18:21
Will do, currently unable to replicate , it stopped happening. Ill re-open when im able to replicate it.

**Comment by froemken** [comment] 2016-08-17 12:13
Hello @lukepolo I currently have the same problem. Did you found a solution for it?

**Comment by lukepolo** [comment] 2016-08-17 12:15
I believe it was because of the remote server, it kept closing / terminating the connection but phpseclib did not notice.

**Comment by froemken** [comment] 2016-08-17 14:47
Seems to be a more random problem.
- Restarting the Webserver helps sometimes
- I work with multiple parallel terminals. Sometimes it helps to close one or two of these windows. Yes...we have a limit of multiple SSH connections configured at server. Can phpseclib handle such limitation with correct error messages?
- We work with an API which creates temporary parallel working passwords for ssh users. Maybe we are "sometimes" too fast with login. After creating the parallel password I currently wait 1 second (sleep(1)) before login().

Last solution seems to work best.

**Comment by terrafrost** [comment] 2016-08-18 19:08
Can you post your server logs? You can get them by doing `define('NET_SSH2_LOGGING', 2);` at the top and `echo $ssh->getLog();` after the failed login attempt.

Thanks!

**Comment by froemken** [comment] 2016-08-18 20:25
Hello TerraFrost, I have send you 2 ServerLogs via Mail just 2 days ago. It was a @php.net E-Mail-Address with a Reference to this ticket. If you can not find that mail inform me if it is save to post the logs, because of the password. Is it logged, too?

**Comment by terrafrost** [comment] 2016-08-18 20:49
I'm not seeing the email :\ I just sent a test email to terrafrost@php.net and got it so idk.

Anyway, the password is filtered out. It's been filtered out of the complex logs since at least 0.3.0:

https://github.com/phpseclib/phpseclib/blob/0.3.0/phpseclib/Net/SSH2.php#L1454

The current version does it a little differently:

https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Net/SSH2.php#L2026

But none-the-less passwords should be filtered out assuming you're not using an ancient version lol

**Comment by bantu** [comment] 2016-11-11 17:33
@froemken Any update on this?

**Comment by froemken** [comment] 2016-11-15 09:13
The maintainer of our SSH-Server has some curious LDAP Integrations. They have solved a lot of bugs in the last months and yes: It was not a bug of phpseclib. You can close this ticket now. Thank you for your help

**Closed** 2016-11-20 15:02 UTC
Labels: bug

**Comment by salahy2** [comment] 2017-10-19 11:19
hello, I am getting the same error, it was working perfectly now it stopped, how did you solve it ? 
i am losing my mind :(

**Comment by terrafrost** [comment] 2017-10-19 12:49
@salahy2 - the fact that you responded to a closed ticket instead of opening a new one may mean subsequent replies may get lost. It might be beneficial for you to open up a new ticket.

Regardless...  can you post your SSH logs? You can get them by doing `define('NET_SSH2_LOGGING', 2);` at the top and `echo $ssh->getLog();` after the failed login attempt.

**Comment by crystalik** [comment] 2019-01-08 05:15
This happens if the connection is terminated. Just do 'service networking restart' while any remote operation (read or write) to repeat the problem. I had it recently.
