### ISSUE TITLE
Different RSA::verify() result in version 2 and 3 (+ compat)

### ISSUE THREAD

**Issue by JanSlabon** [phpseclib/phpseclib#1579] opened 2021-01-08 10:47 UTC
When using the the compat layer for version 2 we're not able to verify signatures which were validated fine in the native version 2.

The test script:

```
<?php

require_once 'vendor/autoload.php';

$key = hex2bin("3082020a0282020100d595c09fbc635612b3ef6a0067d74cb76fa9af62a9272400c2a896f1335b920b88a9accaffe915e38542d296c1a559a586223521da8977030888a8d076910f59489a3a4a10bf950bf2b83278810e4c3bfc027b6b6cb75736cfaabaa83de15c619b8e9f65a60f4cfeba11fb5bf5e93abff68468695948b1843e2e09504281651475f7eff1c30fcb17026f13f04109fc930e489c14a1ef80ec51be6bb73f1679d258c2db535b04f4be82790ac01b4b0e9cb68a9bb5afab4363b5f33ff143ef13d1b2a292a72881d68d765a6c1fc981da0a2644ed284607d19f39802b3967bf9308da1f6515b59a2b0a1c57c14d661a62672f3b9453f931b62c446267d912c0987b7fb4c4fe085e3573ddfd9761ec2c035fa560c6c98343e9d448667b724a919780be2fd8666115d8a75b29e6c1e216cd73a693192f551f72fdf9eac0bb5bda83b11b5159151419249915e6006e6018bc1cda20960d4f1c7df7d401afd322656b4f0810348b8d20d506b08dd8752a0a721efa750b785fb2cb40930d33dd70bd8ad83883470851bd664c648da3f102545f1c54fa803cea5ba3edb51c3b894bd8fbd48d4ed97c251b3eed1d4e636d487a711d3859946acc14f808d777bcc3c5594ac2cd7dcf278ef4e7d3badea740f757a0669f213dadf46e9ff0eeb10720af086ce29e27e0ca2a639f4f3c5825ea5e2774bb3e722ce40e7cf6e2075857797c13d2d50203010001");

$parameters = [
    "sha512",
    "sha512",
    null,
    1
];

$signedData = hex2bin("3182015a301806092a864886f70d010903310b06092a864886f70d010701304f06092a864886f70d0109043142044083cc3c237fa39a617a4e23e2e0760d784f20a9cf2d60225f68f26f1c62c15012d7750d804c07cc11ac256971bfa873e4cfd47846153c00d7fc3d3ca6e78f96e33081ec060b2a864886f70d010910022f3181dc3081d93081d63081d3300d06096086480165030402010500042085fe1c742421ae1f8f4cfa5c2ec0304c2dfecdc13b5884b133a9850c9c024e7d30819f308199a48196308193310b30090603550406130244453116301406035504080c0d4e69656465727361636873656e311f301d060355040a0c16536574617369676e20476d6248202620436f2e204b473120301e06035504030c17446576656c6f706d656e7420616e642054657374696e673129302706092a864886f70d010901161a736574617064662d64656d6f7340736574617369676e2e636f6d020100");
$signatureValue = hex2bin("4fc2a715cd4da1d8805d34ba5d2bc841b73738033182cac7a122fa3e7bb6076b3d647fe254b12ff6e11e2e8ec13c34a5f713891067f9d4ed7fe8364fcdf8cc78147343b88a5d9e38bf9b33d9945a84d10ef758a6bc9d1d16273a811961d17cfec562069fe4d86f0bc56392410be4540404d7bac04797ef99b77af38741b7eac7b968c1e470c2940b6caaca6f0bcb12691c58c758f487d50bd1a4a5d0b08a8cbe446466b5ff64d209efae63545f2e791ef6d59842c614da0878de8be0338359e8a0438edaac82c36b76553f42261eeb2108fc9d66de1258694b330487f0b97010fc95b6e1d995bb5ff01de0147263f9cb1fda2ceb9d81b73bdbaad87534d2dd0eb2f9ba54bfa21b46dd18c7fb9e7b41a7591a4b09041bd90b2fbcbf64e4d3853ee61285eec961dbb399a7c09cc88f6d1b2aaa817ec6f91ef49a531cbf0fad18e0a71fab05de315548fc0eb610cda1756f6bcf02510f1a5ed09eae085478a96a7ebedcd1b62d415936b1af164ce1e3589cb81890368f6981536fbddfa5ecad13ad8642483ea46240769dc0c6ef10b5da56e96bdb322febd6d9633337ac11798b1e9997dbb81d7d61c99a6197ebff7ae72e7e420783dc812496f31aad5026110cbdbbf54fa55a03a26e4369fb1195754ba257d126fed63613186f7c45c6997921dbba12b942c2bb2e46373325ee9f7b9a07bd476d0117a7b75ddcda2a140b461008");

$rsa = new phpseclib\Crypt\RSA();
$rsa->loadKey($key);
$rsa->setHash($parameters[0]);
$rsa->setMGFHash($parameters[1]);
if ($parameters[2] !== null) {
    $rsa->setSaltLength($parameters[2]);
}

var_dump($rsa->verify($signedData, $signatureValue));
```

With a direct dependency to version 2:

    "phpseclib/phpseclib": "^2.0",

This script outputs `bool(true)`.

With the compat layer in use:

        "phpseclib/phpseclib": "^3.0",
        "phpseclib/phpseclib2_compat": "^1.0"

The script outputs `bool(false)`.

**Comment by terrafrost** [comment] 2021-01-08 14:39
A quick work around would be to add `-----BEGIN RSA PUBLIC KEY-----` to the top of the key.

I'm working on a better fix in the mean time.

To be more specific as to what the problem is...

Quoting https://tools.ietf.org/html/rfc8017#section-3.2 ,

```
   For the purposes of this document, an RSA private key may have either
   of two representations.

   1.  The first representation consists of the pair (n, d), where the
       components have the following meanings:

            n       the RSA modulus, a positive integer
            d       the RSA private exponent, a positive integer

   2.  The second representation consists of a quintuple (p, q, dP, dQ,
       qInv) and a (possibly empty) sequence of triplets (r_i, d_i,
       t_i), i = 3, ..., u, one for each prime not in the quintuple,
       where the components have the following meanings:

            p      the first factor, a positive integer
            q      the second factor, a positive integer
            dP     the first factor's CRT exponent, a positive integer
            dQ     the second factor's CRT exponent, a positive integer
            qInv   the (first) CRT coefficient, a positive integer
            r_i    the i-th factor, a positive integer
            d_i    the i-th factor's CRT exponent, a positive integer
            t_i    the i-th factor's CRT coefficient, a positive integer
```
The first representation is the exact same representation that public keys use. So how does phpseclib know if it's supposed to be a public key or a private key if the first representation is used? It guesses. It looks for the word "PUBLIC" in the key and if it finds it it assumes that it's a public key. Otherwise it assumes it's a private key. So phpseclib is assuming that the key being loaded is a private key.

In phpseclib 2.0 if you tried to verify a signature with a private key it'd happily do so using the private key components. Well, it'd do the modular exponentiation with or without the CRT parameters and then it'd verify that the structure was correct.

phpseclib 3.0 is a bit more stringent. You can't perform verify operations with a private key, period.

Anyway, what I'm working on making it do is to revamp the "guessing" method:

- If PUBLIC appears in the key it's a public key
- If PRIVATE appears in the key it's a private key
- If neither appear in the key then "guess" that it's a private key if the CRT parameters are present, otherwise guess that it's a public key. 'cause even tho PKCS1 says that a private key doesn't need to contain the CRT parameters its seems to me like 99% of them do!

I have to go to work, soon, so I won't have any updates on this for a number of hours, but when I get back home, hopefully I can have something committed!

**Comment by JanSlabon** [comment] 2021-01-08 14:48
Thanks for the fast feedback! This is nothing urgent on our end! I just trapped into it and simply wanted to report it. Have a nice weekend! ;-)

**Comment by terrafrost** [comment] 2021-01-09 01:22
This should be working better as of https://github.com/phpseclib/phpseclib/commit/05d934c89f3597d6c3b0a88892ea4f0d76c3ac6a . Thanks!

**Closed** 2021-01-09 01:23 UTC
