### ISSUE TITLE
phpseclib SSH2 write not executing long commands

### ISSUE THREAD

**Issue by dilaniMaheswaran** [phpseclib/phpseclib#1350] opened 2019-03-11 09:22 UTC
I am using phpseclib ssh version 2.0 with laravel.

I am trying to execute an SSH command to a device(firewall). Command is executed when the length is short. When the length is about 2000 characters, command is not being executed.

When I execute the command via cli,it is running perfect. When I reduce length of the same command, that is working as well.

After reading few solutions, I tried to set timeout to 5 seconds. Still, no help.

In the device logs, I can see SSH login and logout. But no activity.

```
$ssh = new SSH2(ip_address);
$ssh->login($user, $password);
$ssh->write($command);
$ssh->setTimeout(5);
$ssh->read()
```

**Comment by terrafrost** [comment] 2019-03-12 04:52
Can you post the SSH logs? You can get them by doing `define('NET_SSH2_LOGGING', 2);` at the top and then `echo $ssh->getLog();` after the `$ssh->read();`.

**Comment by dilaniMaheswaran** [comment] 2019-03-12 05:18
<-\r\n
00000000  53:53:48:2d:32:2e:30:2d:64:5a:64:57:70:76:75:44  SSH-2.0-dZdWpvuD\r\n
00000010  36:0d:0a                                         6..\r\n
\r\n
->\r\n
00000000  53:53:48:2d:32:2e:30:2d:70:68:70:73:65:63:6c:69  SSH-2.0-phpsecli\r\n
00000010  62:5f:32:2e:30:20:28:6f:70:65:6e:73:73:6c:2c:20  b_2.0 (openssl, \r\n
00000020  62:63:6d:61:74:68:29:0d:0a                       bcmath)..\r\n
\r\n
-> NET_SSH2_MSG_KEXINIT (since last: 0.0415, network: 0s)\r\n
00000000  e1:95:9c:71:0b:d1:f5:89:3f:00:d6:a8:1d:82:b9:16  ...q....?.......\r\n
00000010  00:00:00:7e:64:69:66:66:69:65:2d:68:65:6c:6c:6d  ...~diffie-hellm\r\n
00000020  61:6e:2d:67:72:6f:75:70:31:2d:73:68:61:31:2c:64  an-group1-sha1,d\r\n
00000030  69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72  iffie-hellman-gr\r\n
[I HAVE REMOVED TO MAKE IT SHORT]
\r\n
<- NET_SSH2_MSG_KEXINIT (since last: 0.0097, network: 0.0097s)\r\n
00000000  1f:b2:31:95:c5:14:e5:fd:14:16:ab:c6:fe:b3:f1:51  ..1............Q\r\n
00000010  00:00:00:80:63:75:72:76:65:32:35:35:31:39:2d:73  ....curve25519-s\r\n
[I HAVE REMOVED TO MAKE IT SHORT]
\r\n
-> NET_SSH2_MSG_KEXDH_INIT (since last: 0.0201, network: 0s)\r\n
00000000  00:00:01:01:00:ba:a3:a6:9b:4d:e1:0f:bb:0f:9f:f5  .........M......\r\n
[I HAVE REMOVED TO MAKE IT SHORT]
\r\n
<- NET_SSH2_MSG_KEXDH_REPLY (since last: 0.0499, network: 0.0499s)\r\n
00000000  00:00:01:17:00:00:00:07:73:73:68:2d:72:73:61:00  ........ssh-rsa.\r\n
[I HAVE REMOVED TO MAKE IT SHORT]
\r\n
-> NET_SSH2_MSG_NEWKEYS (since last: 0.0287, network: 0s)\r\n
                                                 \r\n
\r\n
<- NET_SSH2_MSG_NEWKEYS (since last: 0, network: 0s)\r\n
                                                 \r\n
\r\n
-> NET_SSH2_MSG_SERVICE_REQUEST (since last: 0.0003, network: 0s)\r\n
00000000  00:00:00:0c:73:73:68:2d:75:73:65:72:61:75:74:68  ....ssh-userauth\r\n
\r\n
<- NET_SSH2_MSG_SERVICE_ACCEPT (since last: 0.0664, network: 0.0663s)\r\n
00000000  00:00:00:0c:73:73:68:2d:75:73:65:72:61:75:74:68  ....ssh-userauth\r\n
\r\n
-> NET_SSH2_MSG_USERAUTH_REQUEST (since last: 0.0171, network: 0s)\r\n
00000000  00:00:00:0b:50:72:6f:76:73:65:72:76:69:63:65:00  ....Provservice.\r\n
00000010  00:00:0e:73:73:68:2d:63:6f:6e:6e:65:63:74:69:6f  ...ssh-connectio\r\n
00000020  6e:00:00:00:09:70:75:62:6c:69:63:6b:65:79:00:00  n....publickey..\r\n
[I HAVE REMOVED TO MAKE IT SHORT]
\r\n
<- NET_SSH2_MSG_USERAUTH_PK_OK (60) (since last: 0.0172, network: 0.0172s)\r\n
00000000  00:00:00:07:73:73:68:2d:72:73:61:00:00:01:17:00  ....ssh-rsa.....\r\n
[I HAVE REMOVED TO MAKE IT SHORT]
\r\n
-> NET_SSH2_MSG_USERAUTH_REQUEST (since last: 0.0628, network: 0s)\r\n
00000000  00:00:00:0b:50:72:6f:76:73:65:72:76:69:63:65:00  ....Provservice.\r\n
00000010  00:00:0e:73:73:68:2d:63:6f:6e:6e:65:63:74:69:6f  ...ssh-connectio\r\n
00000020  6e:00:00:00:09:70:75:62:6c:69:63:6b:65:79:01:00  n....publickey..\r\n
00000030  00:00:07:73:73:68:2d:72:73:61:00:00:01:17:00:00  ...ssh-rsa......\r\n
00000040  00:07:73:73:68:2d:72:73:61:00:00:00:03:01:00:01  ..ssh-rsa.......\r\n
[I HAVE REMOVED TO MAKE IT SHORT]
\r\n
<- NET_SSH2_MSG_USERAUTH_SUCCESS (since last: 0.0169, network: 0.0169s)\r\n
                                                 \r\n
\r\n
-> NET_SSH2_MSG_CHANNEL_OPEN (since last: 0.0002, network: 0s)\r\n
00000000  00:00:00:07:73:65:73:73:69:6f:6e:00:00:00:02:7f  ....session.....\r\n
00000010  ff:ff:ff:00:00:40:00                             .....@.\r\n
\r\n
<- NET_SSH2_MSG_GLOBAL_REQUEST (since last: 0.0166, network: 0.0001s)\r\n
00000000  00:00:00:17:68:6f:73:74:6b:65:79:73:2d:30:30:40  ....hostkeys-00@\r\n
00000010  6f:70:65:6e:73:73:68:2e:63:6f:6d:00:00:00:01:17  openssh.com.....\r\n
00000020  00:00:00:07:73:73:68:2d:72:73:61:00:00:00:03:01  ....ssh-rsa.....\r\n
[I HAVE REMOVED TO MAKE IT SHORT]
\r\n
-> NET_SSH2_MSG_REQUEST_FAILURE (since last: 0.0001, network: 0s)\r\n
                                                 \r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_OPEN_CONFIRMATION (since last: 0.0489, network: 0.0489s)\r\n
00000000  00:00:00:02:00:00:00:00:00:00:00:00:00:00:80:00  ................\r\n
\r\n
-> NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0001, network: 0s)\r\n
00000000  00:00:00:00:00:00:00:07:70:74:79:2d:72:65:71:01  ........pty-req.\r\n
00000010  00:00:00:05:76:74:31:30:30:00:00:00:50:00:00:00  ....vt100...P...\r\n
00000020  18:00:00:00:00:00:00:00:00:00:00:00:01:00        ..............\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_SUCCESS (since last: 0.0164, network: 0.0164s)\r\n
00000000  00:00:00:02                                      ....\r\n
\r\n
-> NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0002, network: 0s)\r\n
00000000  00:00:00:00:00:00:00:05:73:68:65:6c:6c:01        ........shell.\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_WINDOW_ADJUST (since last: 0.0168, network: 0.0001s)\r\n
00000000  00:00:00:02:00:20:00:00                          ..... ..\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_SUCCESS (since last: 0.0001, network: 0s)\r\n
00000000  00:00:00:02                                      ....\r\n
\r\n
-> NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0002, network: 0s)\r\n
00000000  00:00:00:00:00:00:05:92:63:6f:6e:66:69:67:20:67  ........config g\r\n
00000010  6c:6f:62:61:6c:0a:65:78:65:63:20:62:61:74:63:68  lobal.exec batch\r\n
00000020  20:73:74:61:72:74:0a:63:6f:6e:66:20:76:64:6f:6d   start.conf vdom\r\n
00000030  0a:65:64:69:74:20:22:72:6f:6f:74:22:0a:0a:63:6f  .edit "root"..co\r\n
00000040  6e:66:20:66:69:72:65:77:61:6c:6c:20:61:64:64:72  nf firewall addr\r\n
00000050  67:72:70:20:0a:65:64:69:74:20:22:47:52:50:5f:46  grp .edit "GRP_F\r\n
[I HAVE REMOVED TO MAKE IT SHORT]
00000580  31:39:22:20:20:0a:65:6e:64:20:0a:65:78:65:63:20  19"  .end .exec \r\n
00000590  62:61:74:63:68:20:65:6e:64:0a                    batch end.\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0083, network: 0.0001s)\r\n
00000000  00:00:00:02:00:00:00:10:46:57:31:2d:41:4d:53:54  ........FW1-AMST\r\n
00000010  45:52:44:41:4d:20:23:20                          ERDAM # \r\n
\r\n
"""

**Comment by dilaniMaheswaran** [comment] 2019-03-12 05:38
"""
<-\r\n
00000000  53:53:48:2d:32:2e:30:2d:5a:42:66:71:34:30:57:5a  SSH-2.0-ZBfq40WZ\r\n
00000010  46:45:44:59:48:5f:75:0d:0a                       FEDYH_u..\r\n
\r\n
->\r\n
00000000  53:53:48:2d:32:2e:30:2d:70:68:70:73:65:63:6c:69  SSH-2.0-phpsecli\r\n
00000010  62:5f:32:2e:30:20:28:6f:70:65:6e:73:73:6c:2c:20  b_2.0 (openssl, \r\n
00000020  62:63:6d:61:74:68:29:0d:0a                       bcmath)..\r\n
\r\n
-> NET_SSH2_MSG_KEXINIT (since last: 0.2687, network: 0.0002s)\r\n
00000000  58:ae:6f:c7:67:7c:ba:1b:24:12:de:4d:dd:76:b0:21  X.o.g|..$..M.v.!\r\n
[I HAVE REMOVED TO MAKE IT SHORT]
\r\n
<- NET_SSH2_MSG_KEXINIT (since last: 0.1274, network: 0.1272s)\r\n
00000000  d1:3d:81:38:ed:b0:58:f9:e6:b6:b6:d2:bb:a5:71:84  .=.8..X.......q.\r\n
[I HAVE REMOVED TO MAKE IT SHORT]
\r\n
-> NET_SSH2_MSG_KEXDH_INIT (since last: 0.0187, network: 0.0002s)\r\n
[I HAVE REMOVED TO MAKE IT SHORT]                                .;*.\r\n
\r\n
<- NET_SSH2_MSG_KEXDH_REPLY (since last: 0.1532, network: 0.1532s)\r\n
00000000  00:00:01:17:00:00:00:07:73:73:68:2d:72:73:61:00  ........ssh-rsa.\r\n
[I HAVE REMOVED TO MAKE IT SHORT]
-> NET_SSH2_MSG_NEWKEYS (since last: 0.0257, network: 0.0002s)\r\n
                                                 \r\n
\r\n
<- NET_SSH2_MSG_NEWKEYS (since last: 0, network: 0s)\r\n
                                                 \r\n
\r\n
-> NET_SSH2_MSG_SERVICE_REQUEST (since last: 0.0008, network: 0.0002s)\r\n
00000000  00:00:00:0c:73:73:68:2d:75:73:65:72:61:75:74:68  ....ssh-userauth\r\n
\r\n
<- NET_SSH2_MSG_SERVICE_ACCEPT (since last: 0.2924, network: 0.2923s)\r\n
00000000  00:00:00:0c:73:73:68:2d:75:73:65:72:61:75:74:68  ....ssh-userauth\r\n
\r\n
-> NET_SSH2_MSG_USERAUTH_REQUEST (since last: 0.014, network: 0.0002s)\r\n
00000000  00:00:00:0b:50:72:6f:76:73:65:72:76:69:63:65:00  ....Provservice.\r\n
00000010  00:00:0e:73:73:68:2d:63:6f:6e:6e:65:63:74:69:6f  ...ssh-connectio\r\n
00000020  6e:00:00:00:09:70:75:62:6c:69:63:6b:65:79:00:00  n....publickey..\r\n
00000030  00:00:07:73:73:68:2d:72:73:61:00:00:01:17:00:00  ...ssh-rsa......\r\n
00000040  00:07:73:73:68:2d:72:73:61:00:00:00:03:01:00:01  ..ssh-rsa.......\r\n
0[I HAVE REMOVED TO MAKE IT SHORT]
\r\n
<- NET_SSH2_MSG_USERAUTH_PK_OK (60) (since last: 0.1289, network: 0.1289s)\r\n
00000000  00:00:00:07:73:73:68:2d:72:73:61:00:00:01:17:00  ....ssh-rsa.....\r\n
00000010  00:00:07:73:73:68:2d:72:73:61:00:00:00:03:01:00  ...ssh-rsa......\r\n
[I HAVE REMOVED TO MAKE IT SHORT]
\r\n
-> NET_SSH2_MSG_USERAUTH_REQUEST (since last: 0.0665, network: 0.0002s)\r\n
00000000  00:00:00:0b:50:72:6f:76:73:65:72:76:69:63:65:00  ....Provservice.\r\n
00000010  00:00:0e:73:73:68:2d:63:6f:6e:6e:65:63:74:69:6f  ...ssh-connectio\r\n
00000020  6e:00:00:00:09:70:75:62:6c:69:63:6b:65:79:01:00  n....publickey..\r\n
00000030  00:00:07:73:73:68:2d:72:73:61:00:00:01:17:00:00  ...ssh-rsa......\r\n
00000040  00:07:73:73:68:2d:72:73:61:00:00:00:03:01:00:01  ..ssh-rsa.......\r\n
[I HAVE REMOVED TO MAKE IT SHORT]
<- NET_SSH2_MSG_USERAUTH_SUCCESS (since last: 0.1286, network: 0.1285s)\r\n
                                                 \r\n
\r\n
-> NET_SSH2_MSG_CHANNEL_OPEN (since last: 0.0004, network: 0.0003s)\r\n
00000000  00:00:00:07:73:65:73:73:69:6f:6e:00:00:00:02:7f  ....session.....\r\n
00000010  ff:ff:ff:00:00:40:00                             .....@.\r\n
\r\n
<- NET_SSH2_MSG_GLOBAL_REQUEST (since last: 0.1296, network: 0.0002s)\r\n
00000000  00:00:00:17:68:6f:73:74:6b:65:79:73:2d:30:30:40  ....hostkeys-00@\r\n
00000010  6f:70:65:6e:73:73:68:2e:63:6f:6d:00:00:00:01:17  openssh.com.....\r\n
00000020  00:00:00:07:73:73:68:2d:72:73:61:00:00:00:03:01  ....ssh-rsa.....\r\n
[I HAVE REMOVED TO MAKE IT SHORT]
-> NET_SSH2_MSG_REQUEST_FAILURE (since last: 0.001, network: 0.0008s)\r\n
                                                 \r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_OPEN_CONFIRMATION (since last: 0.1328, network: 0.1322s)\r\n
00000000  00:00:00:02:00:00:00:00:00:00:00:00:00:00:80:00  ................\r\n
\r\n
-> NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0026, network: 0.0012s)\r\n
00000000  00:00:00:00:00:00:00:07:70:74:79:2d:72:65:71:01  ........pty-req.\r\n
00000010  00:00:00:05:76:74:31:30:30:00:00:00:50:00:00:00  ....vt100...P...\r\n
00000020  18:00:00:00:00:00:00:00:00:00:00:00:01:00        ..............\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_SUCCESS (since last: 0.1274, network: 0.1273s)\r\n
00000000  00:00:00:02                                      ....\r\n
\r\n
-> NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0003, network: 0.0002s)\r\n
00000000  00:00:00:00:00:00:00:05:73:68:65:6c:6c:01        ........shell.\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_WINDOW_ADJUST (since last: 0.128, network: 0.0001s)\r\n
00000000  00:00:00:02:00:20:00:00                          ..... ..\r\n
\r\n
<- NET_SSH2_MSG_CHANNEL_SUCCESS (since last: 0.0002, network: 0s)\r\n
00000000  00:00:00:02                                      ....\r\n
\r\n
-> NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0.0003s)\r\n
00000000  00:00:00:00:00:00:06:d7:63:6f:6e:66:69:67:20:67  ........config g\r\n
00000010  6c:6f:62:61:6c:0a:65:78:65:63:20:62:61:74:63:68  lobal.exec batch\r\n
00000020  20:73:74:61:72:74:0a:63:6f:6e:66:20:76:64:6f:6d   start.conf vdom\r\n
[I HAVE REMOVED TO MAKE IT SHORT]
\r\n

**<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.1246, network: 0.0008s)\r\n
00000000  00:00:00:02:00:00:00:01:63                       ........c\r\n
\r\n
[SIMILAR DATA LOGS FOR ABOUT 500 LINES]

<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0001, network: 0s)\r\n
00000000  00:00:00:02:00:00:00:22:0d:0a:45:78:69:74:20:61  ......."..Exit a\r\n
00000010  6e:64:20:72:75:6e:20:62:61:74:63:68:20:63:6f:6d  nd run batch com\r\n
00000020  6d:61:6e:64:73:2e:2e:2e:0d:0a                    mands.....\r\n
\r\n
"""** 

I find the bold text missing in the failure case

**Comment by terrafrost** [comment] 2019-03-12 13:25
I think the feedback you're getting on stackoverflow is good:

https://stackoverflow.com/questions/55098095/phpseclib-ssh2-write-not-executing-long-command

I guess the only other thing I can add to what neubert said is...  *are* you able to run the command with a shell script? Over an interactive shell you can send [special characters](http://phpseclib.sourceforge.net/ssh/examples.html#f1f2), you can have [ANSI escape codes](http://phpseclib.sourceforge.net/ssh/examples.html#top), etc. You don't have as much versatility in the data that you can send / receive via a shell script as you do via the bash prompt. The extra versatility raw bash provides can sometimes make bash a little harder to reason about.

Anyway, it's just a thought. All I can do, in lieu of the actual command, is to chime in with thoughts such as these...

**Comment by dilaniMaheswaran** [comment] 2019-03-13 11:02
No luck on this one as well. 

My command is basically trying to add members to a group in fortigate firewall. When it tries to add more members, no activity is being performed on the firewall. When I add few members, activity is successful. I am using SSH to connect to the firewall and execute the command.

```
config global

 exec batch start

 conf vdom
 edit [PORT_VDOM]

 conf firewall addrgrp  
 edit "[GROUP_NAME]"  
 set member "[MEMBERS]"
 end  
 exec batch end
```

This is the command I am executing. [MEMBERS] are list of values seprated by space.  When I add about 20 members, there is activity. When I add about 35 members where the length of the command increases, no activity is seen on the firewall. If I execute the same command on the CLI directly , it is working fine.

**Comment by terrafrost** [comment] 2019-03-13 14:02
I don't have a fortigate firewall I can conduct tests on and I'm disinclined to buy one.

In the most recent stackoverflow post it was suggested that you email me since confidentiality was an issue. That'd work.

Alternatively, some people have have gotten their problems resolved by giving me full SSH access. This most recently happened with #1343 and the fact that the poster did that enabled me to implement this fix:

https://github.com/phpseclib/phpseclib/commit/fce6063de6844904b0a3facf3ba63a17f6f7b69d

tbh idk that I would have been able to come up with that as a fix had it not been for the poster willing to give me SSH access.

Note that this isn't to say that this is definitively a bug in phpseclib but alas there is waaaay too little info here with which to make a diagnosis.

**Comment by dilaniMaheswaran** [comment] 2019-03-14 10:21
I have requested permission to share the logs and the commands with you. I will share the logs if it is approved. 

In the meanwhile I would like to know if there is any limitation on the length of the command I can pass in $ssh->write() .

In my case my command has about 2000+ characters that includes space, _ , .  '\n' and double quotations.

**Comment by terrafrost** [comment] 2019-03-16 15:03
{quote}
In the meanwhile I would like to know if there is any limitation on the length of the command I can pass in $ssh->write() .
{quote}
Not in-so-far as phpseclib is concerned. Case in point:

```php
$ssh->exec('echo ' . str_repeat('z', 3000) . ' > test.txt');
```

That results in a 3001 byte file being created. The extra byte is "\n".

Keep in mind that, in all likelihood, when you're running the command in PuTTY you're likely doing so through an interactive shell. `exec()` is *not* an interactive shell and it's possible that the firewall that you're connecting to is, itself, imposing a limit that phpseclib isn't.

If you want to do an interactive shell with phpseclib do `$ssh->write()`. Here's an example of how to do interactive shells:

http://phpseclib.sourceforge.net/ssh/examples.html#interactive

**Comment by terrafrost** [comment] 2019-03-16 15:03
> In the meanwhile I would like to know if there is any limitation on the length of the command I can pass in $ssh->write() .

Not in-so-far as phpseclib is concerned. Case in point:

```php
$ssh->exec('echo ' . str_repeat('z', 3000) . ' > test.txt');
```

That results in a 3001 byte file being created. The extra byte is "\n".

Keep in mind that, in all likelihood, when you're running the command in PuTTY you're likely doing so through an interactive shell. `exec()` is *not* an interactive shell and it's possible that the firewall that you're connecting to is, itself, imposing a limit that phpseclib isn't.

If you want to do an interactive shell with phpseclib do `$ssh->write()`. Here's an example of how to do interactive shells:

http://phpseclib.sourceforge.net/ssh/examples.html#interactive

**Comment by terrafrost** [comment] 2019-03-16 15:17
Scratch my last post - you are using interactive mode lol. But still...  it's not an issue in interactive mode either:

```php
$ssh->read('[prompt]');
$ssh->write('echo ' . str_repeat('z', 3000) . " > test.txt\n");
$ssh->read('[prompt]');
```
That yields the same result - a 3001 byte file.

idk if the firewall has a prompt but, if it does, it might be worthwhile to wait for the prompt as I'm doing in my example. In PuTTY you're probably only entering the command in after the prompt becomes available. If there's a few second delay before the server sends you the prompt that could be causing issues.

Outside of that the two big differences I'm aware of with PuTTY vs phpseclib are as follows:

- different terminal modes are used. phpseclib uses vt100 whereas PuTTY, I believe, uses xterm. This mainly affects the ANSI escape codes but who knows...  maybe it has additional impact on additional firewall's.
- PuTTY sends characters one packet at a time. Quoting the stackoverflow.com post, "_don't send the command in one big giant `$ssh->write()` but, instead, send it a character at a time. eg. `for ($i = 0; $i < strlen($command); $i++) $ssh->write($command[$i]);`_"

Regardless, there is no limit on the size of the commands that you can send to the server. At least not on the phpseclib side of things. To understand why it's working with PuTTY and not phpseclib the logs would really help.

**Comment by dilaniMaheswaran** [comment] 2019-03-24 09:43
Thanks for the update.  I did a test to write my exact command to a file on my localhost. It did write to the file when I excluded \n from my command. When my command had "\n", file was still empty. I am assuming that is something to do with \n and echo.

Here is my code on laravel 5.4 php version 7.0

```
$ssh = new SSH2('127.0.0.1');
if (!$ssh->login('username', 'password')) {
    dd('Login Failed');
}

$ssh->read();

$command = "Config global\n Exec batch start\n conf vdom\n edit 'port'\n \n conf firewall addrgrp \n edit 'GRP_FAKE_ONLY' \n set member 'DEMO _1234578' 'DEMO 2558' 'PT. DEMO _2541' 'DEMO._870773932527' (2000 chars similar to this)  \n end \n exec batch end\n"; // refer to the command I have given in my example above.

$ssh->write('echo ' . $command . " > \var\www\html\test.txt\n");
$ssh->read();
```

Above code wrote nothing to the file, but it did when I removed \n (all new line characters from my command).

**Comment by terrafrost** [comment] 2019-03-25 02:55
What you're asking is more of a Linux / BASH question than it is an SSH question but, none-the-less, I think the following link may provide some insight:

https://stackoverflow.com/questions/20536112/how-to-insert-a-new-line-in-linux-shell-script/20538015

Mind you, that's all specific to `echo` - not to the firewall command(s) you're trying to run. To really know why PuTTY works and phpseclib doesn't I'd need to see the SSH logs.

For fun, I cracked open PuTTY to see how it behaved with `ls -latr`:

```
Incoming packet #0x39, type 94 / 0x5e (SSH2_MSG_CHANNEL_DATA)
  00000000  00 00 01 00 00 00 00 01 6c                       ........l
Outgoing packet #0xb, type 94 / 0x5e (SSH2_MSG_CHANNEL_DATA)
  00000000  00 00 00 00 00 00 00 01 73                       ........s
Incoming packet #0x3a, type 94 / 0x5e (SSH2_MSG_CHANNEL_DATA)
  00000000  00 00 01 00 00 00 00 01 73                       ........s
Outgoing packet #0xc, type 94 / 0x5e (SSH2_MSG_CHANNEL_DATA)
  00000000  00 00 00 00 00 00 00 01 20                       ........ 
Incoming packet #0x3b, type 94 / 0x5e (SSH2_MSG_CHANNEL_DATA)
  00000000  00 00 01 00 00 00 00 01 20                       ........ 
Outgoing packet #0xd, type 94 / 0x5e (SSH2_MSG_CHANNEL_DATA)
  00000000  00 00 00 00 00 00 00 01 2d                       ........-
Incoming packet #0x3c, type 94 / 0x5e (SSH2_MSG_CHANNEL_DATA)
  00000000  00 00 01 00 00 00 00 01 2d                       ........-
Outgoing packet #0xe, type 94 / 0x5e (SSH2_MSG_CHANNEL_DATA)
  00000000  00 00 00 00 00 00 00 01 6c                       ........l
Incoming packet #0x3d, type 94 / 0x5e (SSH2_MSG_CHANNEL_DATA)
  00000000  00 00 01 00 00 00 00 01 6c                       ........l
Outgoing packet #0xf, type 94 / 0x5e (SSH2_MSG_CHANNEL_DATA)
  00000000  00 00 00 00 00 00 00 01 61                       ........a
Incoming packet #0x3e, type 94 / 0x5e (SSH2_MSG_CHANNEL_DATA)
  00000000  00 00 01 00 00 00 00 01 61                       ........a
Outgoing packet #0x10, type 94 / 0x5e (SSH2_MSG_CHANNEL_DATA)
  00000000  00 00 00 00 00 00 00 01 74                       ........t
Incoming packet #0x3f, type 94 / 0x5e (SSH2_MSG_CHANNEL_DATA)
  00000000  00 00 01 00 00 00 00 01 74                       ........t
Outgoing packet #0x11, type 94 / 0x5e (SSH2_MSG_CHANNEL_DATA)
  00000000  00 00 00 00 00 00 00 01 72                       ........r
Incoming packet #0x40, type 94 / 0x5e (SSH2_MSG_CHANNEL_DATA)
  00000000  00 00 01 00 00 00 00 01 72                       ........r
Outgoing packet #0x12, type 94 / 0x5e (SSH2_MSG_CHANNEL_DATA)
  00000000  00 00 00 00 00 00 00 01 0d                       .........
```
So PuTTY sends a byte and reads a byte back. So not only does it not send the full command in one string - it gets a response after every keystroke. ie. it's echo'ing every key stroke back.

I cannot fathom this actually fixing anything but I guess you could try to send a byte and then for every byte that you send try reading a byte back.

Like I said, I cannot imagine that fixing anything but it'd result in a more faithful PuTTY reproduction I guess...

**Comment by dilaniMaheswaran** [comment] 2019-04-08 13:03
I have shared the logs via email.

**Comment by terrafrost** [comment] 2019-04-08 13:05
Got it! I'm about to head off to work but I'll try to take a look either this evening or in the next few days as time permits (I'm in the UTC-6 timezone FWIW)

**Comment by dilaniMaheswaran** [comment] 2019-05-01 05:15
Hi,
Thank you for your support.

Issue ended up being the network path between our server and the firewall. All good with the script.
Once again, thank you for your time and support.

**Comment by terrafrost** [comment] 2019-05-01 13:07
Good to hear!

Thanks for the update!

**Closed by terrafrost** 2019-05-01 13:07 UTC
