### ISSUE TITLE
mcrypt_list_algorithms is deprecated

### ISSUE THREAD

**Issue by Frittenfett** [phpseclib/phpseclib#1629] opened 2021-03-19 13:01 UTC
Hey,
file: phpseclib/phpseclib/Crypt/Common/SymmetricKey.php

```
            case self::ENGINE_MCRYPT:
                return $this->cipher_name_mcrypt &&
                       extension_loaded('mcrypt') &&
                       in_array($this->cipher_name_mcrypt, @mcrypt_list_algorithms());
```

This won't work on php 7.4 in strict mode:
`Function mcrypt_list_algorithms() is deprecated`

You should just use your own internal function for this LUL:
`in_array($this->cipher_name_mcrypt, phpseclib_mcrypt_list_algorithms());`

**Comment by terrafrost** [comment] 2021-03-19 16:04
When mcrypt is available it offers such a SIGNIFICNAT speed increase that it is impossible to ignore. I'm talking 45x faster than ANY pure-PHP implementation could EVER hope to achieve. And you want me to just ignore that so I can get a warm fuzzy feeling on the inside that deprecated methods aren't being used? Sorry, but ain't going to happen. See https://github.com/phpseclib/phpseclib/issues/1028#issuecomment-242739527 for a more in depth elaboration.

This is also a dupe of #1512, #1500, #1368, #1229, #1228, #1148, #1134, #1067, #1028, etc

**Closed by terrafrost** 2021-03-19 16:04 UTC

**Comment by terrafrost** [comment] 2021-03-19 16:20
You're also, in all likelihood, getting that error because you're using a custom error handler.

Overall, this leaves us at a bit of an impasse. The two options that I see are:

- Remove mcrypt support all together and let phpseclib take HUUUGE performance hit
- Let it stay, which breaks things for people using custom error handlers

Both options are suboptimal.

**Comment by terrafrost** [comment] 2021-03-19 16:35
In doing some testing it looks like phpseclib implementing it's own custom error handler might be a very good solution. The old error handler can be restored after the phpseclib error handler has been enabled.

Sample code:

```
<?php

set_error_handler(function($errno, $errstr) { throw new Exception($errstr); });

$old = set_error_handler(function() {});

user_error('zzz');

set_error_handler($old);

try {
    user_error('zzz');
} catch (Exception $e) {
    echo "exception caught";
}
```
I'll try to implement something like this. That should give us the best of both. People still get the performance boost of mcrypt whilst also enabling custom error handlers.

**Comment by terrafrost** [comment] 2021-03-20 11:42
https://github.com/phpseclib/phpseclib/commit/e209db78b80c738f20c1c44a69d4c208fd7bdca9

Custom error handlers are now used, which I believe should "fix" the issue for those encountering it.

(for the record, I hadn't pursued this before because I didn't know you can restore the old error handler until just a few days ago)
